INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (1,'Baguette 🥖 – Iconic French bread known for its crispy crust and fluffy interior'),
	 (1,'Croissant 🥐 – Buttery and flaky pastry, perfect for breakfast with coffee'),
	 (1,'Coq au Vin 🍷 – Chicken slowly braised in red wine with mushrooms and onions'),
	 (1,'Ratatouille 🥒 – A Provençal vegetable stew made with zucchini, eggplant, and tomatoes'),
	 (1,'Bouillabaisse 🐟 – Traditional fish stew from Marseille, flavored with herbs and saffron'),
	 (1,'Quiche Lorraine 🥚 – Savory pie with eggs, cream, cheese, and bacon'),
	 (1,'Crêpes 🍓 – Thin pancakes filled with sweet or savory ingredients, a street food classic'),
	 (2,'Paella 🥘 – Traditional Valencian rice dish with saffron, seafood, or meat'),
	 (2,'Tortilla Española 🍳 – Spanish omelette made with potatoes and onions'),
	 (2,'Jamón Ibérico 🐖 – Cured Iberian ham, thinly sliced and full of flavor');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (2,'Gazpacho 🍅 – Cold tomato-based soup, perfect for hot days'),
	 (2,'Patatas Bravas 🍟 – Fried potatoes served with spicy tomato sauce and aioli'),
	 (2,'Churros con Chocolate 🍩 – Fried dough pastries dipped in thick hot chocolate'),
	 (2,'Pulpo a la Gallega 🐙 – Galician-style octopus seasoned with paprika, salt, and olive oil'),
	 (3,'Pasta 🍝 – A staple of Italian cuisine, with famous dishes like Carbonara, Bolognese, and Pesto Pasta'),
	 (3,'Pizza 🍕 – Originally from Naples, the Margherita pizza is a global favorite'),
	 (3,'Gelato 🍦 – Rich and creamy Italian ice cream with intense flavors'),
	 (3,'Tiramisu 🎂 – A beloved dessert made with coffee, mascarpone, and cocoa'),
	 (3,'Maritozzi 🥯 – A soft, lightly sweetened brioche bun filled with fresh whipped cream, a Roman favorite often enjoyed with espresso'),
	 (3,'Lasagna 🧀 – Layered pasta with meat, cheese, and tomato sauce, baked to perfection');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (3,'Risotto 🥄 – Creamy rice dish often cooked with broth, cheese, and mushrooms'),
	 (4,'Fish and Chips 🐟🍟 – Fried battered fish with crispy chips, served with malt vinegar'),
	 (4,'Shepherd’s Pie 🥧 – Savory pie made with minced lamb and topped with mashed potatoes'),
	 (4,'Full English Breakfast 🍳 – Hearty breakfast with eggs, bacon, sausage, beans, and toast'),
	 (4,'Sunday Roast 🍗 – Roast meat with potatoes, Yorkshire pudding, and gravy'),
	 (4,'Bangers and Mash 🥔 – Sausages served with mashed potatoes and onion gravy'),
	 (4,'Sticky Toffee Pudding 🍮 – Moist sponge cake with dates and toffee sauce'),
	 (4,'Cornish Pasty 🥟 – Baked pastry filled with meat, potatoes, and vegetables'),
	 (5,'Wiener Schnitzel 🍽️ – Breaded and fried veal cutlet, a national dish of Austria'),
	 (5,'Tafelspitz 🥩 – Boiled beef served with horseradish and apple-horseradish sauce');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (5,'Apfelstrudel 🍏 – Thin pastry filled with spiced apples and raisins'),
	 (5,'Sachertorte 🍫 – Dense chocolate cake with a layer of apricot jam'),
	 (5,'Kaiserschmarrn 🥞 – Fluffy shredded pancakes served with plum compote'),
	 (5,'Gulasch 🍲 – Hearty stew of meat and paprika, influenced by Hungarian cuisine'),
	 (5,'Knödel 🥔 – Dumplings made from potatoes or bread, served as a side dish'),
	 (6,'Shopska Salad 🥗 – Refreshing salad with tomatoes, cucumbers, onions, and feta cheese'),
	 (6,'Banitsa 🧀 – Baked pastry filled with cheese and eggs'),
	 (6,'Kavarma 🍲 – Slow-cooked stew with pork or chicken and vegetables'),
	 (6,'Tarator 🥒 – Cold yogurt soup with cucumbers, garlic, and dill'),
	 (6,'Kebapche 🌭 – Grilled minced meat sausages, similar to kebabs');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (6,'Lyutenitsa 🍅 – Spicy vegetable relish made from tomatoes and peppers'),
	 (6,'Moussaka 🥘 – Baked dish with layers of potatoes, minced meat, and eggs'),
	 (7,'Swedish Meatballs (Köttbullar) 🍲 - Small meatballs served with lingonberry sauce and creamy gravy'),
	 (7,'Grav lax 🍣 - Cured salmon seasoned with dill, often served with mustard sauce'),
	 (7,'Pyttipanna 🍳 - Diced potatoes, meat, and onions fried together, topped with a fried egg'),
	 (7,'Knäckebröd 🍞 - Crispbread, a traditional Swedish flatbread'),
	 (7,'Semla 🍩 - Sweet bun filled with almond paste and whipped cream, enjoyed before Lent'),
	 (7,'Raggmunk 🥔 - Potato pancakes served with lingonberries or pork'),
	 (7,'Janssons frestelse 🥔 - Creamy casserole made with sprats, potatoes, onions, and cream, a traditional Christmas dish'),
	 (8,'Koshari 🍚 – A hearty mix of rice, lentils, pasta, and chickpeas topped with tomato sauce and crispy onions');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (8,'Ful Medames 🥣 – Slow-cooked fava beans seasoned with olive oil, garlic, and lemon juice, often eaten for breakfast'),
	 (8,'Molokhia 🍲 – A green soup made from jute leaves, cooked with garlic and coriander, typically served with rice or bread'),
	 (8,'Mahshi 🍆 – Vegetables like eggplant, zucchini, and bell peppers stuffed with spiced rice and herbs'),
	 (8,'Fattah 🍖 – A festive dish of layered rice, bread, and meat, topped with a garlic vinegar sauce'),
	 (8,'Ta`ameya (Egyptian Falafel) 🧆 – Deep-fried patties made from ground fava beans and herbs, crispy on the outside and soft inside'),
	 (8,'Roz Bel Laban 🍮 – Creamy rice pudding flavored with vanilla and topped with nuts or cinnamon'),
	 (9,'Tagine 🍲 – Slow-cooked stew named after the earthenware pot it is cooked in, combining meat, poultry, or fish with vegetables and aromatic spices'),
	 (9,'Couscous 🍚 – Steamed semolina grains typically served with a stew of meat and vegetables'),
	 (9,'Harira 🥣 – A rich soup made with tomatoes, lentils, chickpeas, and meat, often enjoyed during Ramadan'),
	 (9,'B`stilla (Pastilla) 🥧 – A savory-sweet pie filled with pigeon or chicken, almonds, and spices, wrapped in thin pastry and dusted with powdered sugar and cinnamon');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (9,'Mechoui 🍖 – Slow-roasted lamb, seasoned with herbs and spices, traditionally cooked whole'),
	 (9,'Zaalouk 🍆 – A smoky eggplant and tomato salad flavored with garlic and spices'),
	 (9,'Chebakia 🍯 – Sesame cookies shaped into flowers, fried, and coated with honey, commonly eaten during Ramadan'),
	 (10,'Biltong 🥩 – Air-dried, cured meat, similar to jerky, seasoned with various spices'),
	 (10,'Boerewors 🌭 – A coiled sausage made from minced beef and spices, traditionally grilled'),
	 (10,'Bobotie 🍲 – A spiced minced meat baked with an egg-based topping, often served with yellow rice'),
	 (10,'Bunny Chow 🍛 – A hollowed-out loaf of bread filled with spicy curry, originating from Durban`s Indian community'),
	 (10,'Malva Pudding 🍰 – A sweet, spongy apricot-flavored dessert served with a creamy sauce'),
	 (10,'Chakalaka 🥗 – A spicy vegetable relish made with tomatoes, onions, carrots, and peppers, often served with bread or pap'),
	 (10,'Koeksisters 🍩 – Deep-fried dough pastries soaked in sweet syrup, crispy on the outside and syrupy inside');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (11,'Ugali 🍚 – A staple maize flour dish, often served with vegetables or meat stew'),
	 (11,'Nyama Choma 🍖 – Grilled meat (usually goat or beef), a social favorite often served with kachumbari'),
	 (11,'Sukuma Wiki 🥬 – Collard greens sautéed with onions and tomatoes, served with ugali'),
	 (11,'Chapati 🫓 – A soft, flaky flatbread introduced from Indian cuisine, now a Kenyan essential'),
	 (11,'Githeri 🫘 – A hearty mix of boiled maize and beans, sometimes enriched with vegetables or meat'),
	 (11,'Mutura 🌭 – Kenyan-style sausage made from spiced meat and blood, grilled on open flames'),
	 (11,'Mandazi 🍩 – A slightly sweet, fried dough snack, perfect with chai'),
	 (12,'Biltong 🍖 – Air-dried, cured meat (often beef or game) sliced thinly; a popular snack similar to jerky'),
	 (12,'Mopane Worms 🐛 – A traditional delicacy: caterpillars that are dried and then cooked, often served with pap (maize porridge)'),
	 (12,'Potjiekos 🍲 – A slow-cooked stew prepared in a three-legged cast iron pot over an open fire, typically featuring meat and vegetables');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (12,'Kapana 🥩 – Grilled meat, usually beef, sold by street vendors and served with spicy sauces'),
	 (12,'Oshifima 🍚 – A stiff maize porridge, similar to sadza, commonly eaten with meat or vegetable stews'),
	 (12,'Eembe 🍇 – Wild berries that are often used to make traditional juices or fermented into alcoholic beverages'),
	 (12,'Zambezi Bream 🐟 – Freshwater fish from the Zambezi River, typically grilled or fried and served with sides like pap and vegetables'),
	 (13,'Grilled Fish 🐟 – Freshly caught fish, often red snapper, marinated with garlic, ginger, and chilies, then grilled over an open flame'),
	 (13,'Octopus Curry 🐙 – Tender octopus cooked in a rich coconut milk curry with spices like turmeric and cinnamon'),
	 (13,'Shark Chutney 🦈 – Mashed shark meat mixed with bilimbi (a sour fruit), lime, and spices, typically served with rice'),
	 (13,'Ladob 🍠 – A dessert made from ripe plantains or sweet potatoes cooked with coconut milk, sugar, and vanilla'),
	 (13,'Satini 🥥 – A spicy condiment made from grated coconut, chilies, and lime, often accompanying grilled dishes'),
	 (13,'Bouillon Brede 🍲 – A light soup made with leafy greens, garlic, and ginger, usually served as a starter');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (13,'Breadfruit Chips 🍞 – Slices of breadfruit deep-fried until crispy; a popular snack or side dish'),
	 (14,'Hamburger 🍔 – A grilled beef patty served in a bun with various toppings like lettuce, tomato, and cheese; an American classic'),
	 (14,'Hot Dog 🌭 – A cooked sausage, traditionally beef, served in a sliced bun and topped with condiments like mustard and ketchup'),
	 (14,'Apple Pie 🍎 – A sweet pie filled with spiced apples, symbolizing American home cooking'),
	 (14,'Barbecue Ribs 🍖 – Pork or beef ribs slow-cooked and slathered in tangy barbecue sauce; a Southern favorite'),
	 (14,'Clam Chowder 🍲 – A creamy soup made with clams, potatoes, onions, and celery, originating from New England'),
	 (14,'Macaroni and Cheese 🧀 – Elbow macaroni pasta baked in a rich cheese sauce; a comfort food staple'),
	 (14,'Buffalo Wings 🍗 – Deep-fried chicken wings tossed in a spicy buffalo sauce, typically served with celery sticks and blue cheese dressing'),
	 (15,'Poutine 🍟🧀 – French fries topped with cheese curds and smothered in rich gravy'),
	 (15,'Butter Tarts 🥧 – Pastry shells filled with a sweet mixture of butter, sugar, and eggs');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (15,'Nanaimo Bars 🍫 – No-bake dessert bars with layers of wafer, custard, and chocolate'),
	 (15,'Tourtière 🥧 – A savory meat pie traditionally filled with minced pork, veal, or beef'),
	 (15,'Bannock 🍞 – A simple flatbread, historically prepared by Indigenous peoples'),
	 (15,'Montreal-Style Bagels 🥯 – Slightly sweeter and denser than their New York counterparts, often topped with sesame or poppy seeds'),
	 (15,'Peameal Bacon Sandwich 🍽️ – Cured pork loin rolled in cornmeal, sliced, and served in a sandwich, often with mustard'),
	 (16,'Tacos al Pastor 🌮 – Marinated pork cooked on a vertical spit, served on corn tortillas with pineapple, onions, and cilantro'),
	 (16,'Mole Poblano 🍗 – A rich, complex sauce made from chiles, chocolate, and spices, typically served over turkey or chicken'),
	 (16,'Chiles en Nogada 🌶️ – Poblano chiles stuffed with a savory-sweet picadillo, topped with walnut sauce and pomegranate seeds'),
	 (16,'Pozole 🍲 – A hearty hominy stew made with pork or chicken, garnished with shredded cabbage, radishes, lime, and oregano'),
	 (16,'Tamales 🌽 – Corn dough filled with meats, cheeses, or other fillings, wrapped in corn husks and steamed');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (16,'Elote 🌽🧀 – Grilled corn on the cob slathered with mayonnaise, cheese, chili powder, and lime juice'),
	 (16,'Guacamole 🥑 – A creamy dip made from mashed avocados, lime juice, onions, cilantro, and tomatoes, usually served with tortilla chips'),
	 (17,'La Bandera Dominicana 🍚🍖 – The national dish consisting of white rice, red beans, and stewed meat'),
	 (17,'Sancocho 🥘 – A hearty stew made with various meats, root vegetables, and plantains'),
	 (17,'Mangú 🍌 – Mashed green plantains typically served with sautéed red onions'),
	 (17,'Mofongo 🥣 – Fried green plantains mashed with garlic and pork cracklings'),
	 (17,'Tostones 🍌 – Twice-fried green plantain slices, crispy on the outside and soft inside'),
	 (17,'Habichuelas con Dulce 🍨 – A sweet dessert made from red beans, coconut milk, sugar, and spices'),
	 (17,'Pica Pollo 🍗 – Dominican-style fried chicken, seasoned and deep-fried to perfection'),
	 (18,'Conch Fritters 🐚 – Deep-fried balls of conch meat mixed with batter and spices');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (18,'Cracked Conch 🍤 – Tenderized conch meat, breaded and fried until crispy'),
	 (18,'Rock Lobsters 🦞 – Grilled or steamed spiny lobsters, often served with butter'),
	 (18,'Bahamian Stew Fish 🐟 – A hearty stew featuring fish, tomatoes, and spices'),
	 (18,'Johnny Cake 🍞 – A dense, slightly sweet bread, often served as a side'),
	 (18,'Peas `n Rice 🍚 – Rice cooked with pigeon peas, tomatoes, and spices'),
	 (18,'Guava Duff 🍰 – A dessert made from guava fruit rolled into dough and served with a sweet sauce'),
	 (19,'Peking Duck 🦆 – Crispy roasted duck served with thin pancakes, hoisin sauce, and sliced scallions'),
	 (19,'Dim Sum 🥟 – An assortment of bite-sized dishes like dumplings and buns, traditionally enjoyed during brunch'),
	 (19,'Kung Pao Chicken 🌶️ – A spicy stir-fry dish made with chicken, peanuts, and chili peppers'),
	 (19,'Chow Mein 🍜 – Stir-fried noodles mixed with vegetables and often meat or tofu');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (19,'Jiaozi 🥟 – Chinese dumplings filled with minced meat and vegetables, either boiled, steamed, or fried'),
	 (19,'Hot Pot 🍲 – A communal meal where diners cook raw ingredients in a simmering pot of flavored broth'),
	 (19,'Moon Cakes 🥮 – Dense pastries filled with sweet bean paste or lotus seed paste, traditionally eaten during the Mid-Autumn Festival'),
	 (20,'Biryani 🍛 – A fragrant mixed rice dish made with basmati rice, spices, and marinated meat or vegetables, layered and cooked to perfection'),
	 (20,'Masala Dosa 🥞 – A crispy, fermented rice and lentil crepe filled with spiced potato mixture, served with chutneys and sambar'),
	 (20,'Butter Chicken 🍗 – Tender chicken pieces cooked in a rich, creamy tomato-based gravy, flavored with aromatic spices'),
	 (20,'Rogan Josh 🍖 – A flavorful Kashmiri curry made with tender lamb or goat meat, cooked in a gravy of yogurt and aromatic spices'),
	 (20,'Chole Bhature 🍽️ – A popular North Indian dish consisting of spicy chickpea curry served with fluffy deep-fried bread'),
	 (20,'Pani Puri 🥟 – Crispy hollow puris filled with spicy tamarind water, mashed potatoes, and chickpeas, a favorite street food'),
	 (20,'Gulab Jamun 🍬 – Deep-fried milk-solid balls soaked in a sweet cardamom and rose-flavored sugar syrup');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (21,'Nasi Goreng 🍚 – Indonesia` take on fried rice, often accompanied by a fried egg on top'),
	 (21,'Rendang 🥩 – A slow-cooked dry curry featuring tender beef simmered in coconut milk and spices'),
	 (21,'Satay 🍢 – Skewered and grilled meat served with a rich peanut sauce'),
	 (21,'Gado-Gado 🥗 – A salad of mixed vegetables, tofu, and hard-boiled eggs, topped with peanut sauce'),
	 (21,'Soto 🥣 – A traditional soup with variations across regions, commonly featuring broth, meat, and vegetables'),
	 (21,'Bakso 🍲 – Meatball soup served with noodles, tofu, and sometimes eggs'),
	 (21,'Martabak Manis 🥞 – A sweet, thick pancake filled with chocolate, cheese, or peanuts'),
	 (22,'Tom Yum Goong 🍤 – A spicy and sour shrimp soup flavored with lemongrass, kaffir lime leaves, and galangal'),
	 (22,'Pad Thai 🍜 – Stir-fried rice noodles with eggs, tofu, shrimp, and flavored with tamarind pulp and fish sauce'),
	 (22,'Green Curry 🍛 – A spicy curry made with green chili paste, coconut milk, and often includes chicken or fish balls');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (22,'Som Tum 🥗 – A refreshing green papaya salad mixed with tomatoes, peanuts, and a tangy lime dressing'),
	 (22,'Massaman Curry 🍲 – A rich, coconut-based curry with tender chunks of meat and potatoes, influenced by Thai-Muslim cuisine'),
	 (22,'Mango Sticky Rice 🍚🥭 – Sweet glutinous rice served with ripe mango slices and drizzled with coconut milk'),
	 (22,'Tom Kha Gai 🍲 – A creamy coconut soup with chicken, infused with galangal, lemongrass, and kaffir lime leaves'),
	 (23,'Sushi 🍣 – Vinegared rice paired with fresh seafood or vegetables, a quintessential Japanese dish'),
	 (23,'Ramen 🍜 – Noodle soup with flavorful broths, topped with ingredients like sliced pork, seaweed, and green onions'),
	 (23,'Tempura 🍤 – Lightly battered and deep-fried seafood or vegetables, known for its crispy texture'),
	 (23,'Okonomiyaki 🥞 – Savory pancakes filled with cabbage, meat, and topped with a variety of condiments'),
	 (23,'Udon 🍜 – Thick wheat noodles served in a savory broth, often garnished with tempura or green onions'),
	 (23,'Yakitori 🍢 – Grilled chicken skewers seasoned with salt or tare sauce, a popular street food');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (23,'Miso Soup 🍲 – A traditional soup made from miso paste, dashi, and various ingredients like tofu and seaweed'),
	 (24,'Al Harees 🍲 – A slow-cooked dish of wheat and meat, seasoned and baked to a porridge-like consistency'),
	 (24,'Al Machboos 🍛 – A spiced rice dish with meat (often chicken or lamb), tomatoes, and vegetables'),
	 (24,'Shawarma 🌯 – Marinated meat (usually chicken or beef) roasted on a spit, sliced, and wrapped in pita bread with garlic sauce'),
	 (24,'Stuffed Camel 🐪 – A traditional dish prepared for special occasions, involving a whole camel stuffed with various ingredients'),
	 (24,'Luqaimat 🍩 – Deep-fried dough balls drizzled with date syrup, often enjoyed as a dessert'),
	 (24,'Balaleet 🍝 – Sweetened vermicelli noodles topped with a thin omelette, blending sweet and savory flavors'),
	 (24,'Quzi 🍖 – Roasted lamb or goat served over spiced rice and garnished with nuts and raisins'),
	 (25,'Hainanese Chicken Rice 🍚 – Tender poached chicken served over fragrant rice, accompanied by chili sauce and ginger paste'),
	 (25,'Chilli Crab 🦀 – Succulent crab stir-fried in a tangy, spicy tomato-based sauce, best enjoyed with mantou buns');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (25,'Laksa 🍜 – A spicy noodle soup with a coconut milk base, featuring rice noodles, shrimp, and tofu puffs'),
	 (25,'Char Kway Teow 🍳 – Stir-fried flat rice noodles with eggs, Chinese sausage, fish cake, and prawns, infused with a smoky flavor'),
	 (25,'Hokkien Mee 🍤 – A mix of egg and rice noodles stir-fried with prawns, squid, and a rich seafood broth'),
	 (25,'Satay 🍢 – Grilled skewers of marinated meat, served with a flavorful peanut sauce'),
	 (25,'Kaya Toast 🍞 – Toasted bread spread with kaya (a sweet coconut and egg jam), typically enjoyed with soft-boiled eggs and coffee'),
	 (26,'Mas Huni 🥥🐟 – A traditional Maldivian breakfast with tuna, coconut, onion, and chili, served with flatbread'),
	 (26,'Garudhiya 🍲 – Fish soup served with rice, lime, chili, and onions'),
	 (26,'Fried Tuna 🐟🍚 – Fried tuna served with rice, a popular Maldivian dish'),
	 (26,'Boshi Mashuni 🍌🥥 – A dish made from bananas, coconut, and spices'),
	 (26,'Hedhika 🍴 – Savory snacks, often served with tea');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (26,'Maldivian Fish Curry 🍛🐠 – Fish curry made with local fish and spices'),
	 (26,'Rihaakuru 🐟🍚 – A thick fish paste served with rice or flatbread'),
	 (27,'Feijoada 🍲 – A rich black bean stew with pork and beef, served with rice'),
	 (27,'Pão de Queijo 🧀🥖 – Small cheese bread rolls, crispy on the outside, soft on the inside'),
	 (27,'Coxinha 🍗🥐 – Fried dough filled with shredded chicken, shaped like a drumstick'),
	 (27,'Brigadeiro 🍫 – A chocolate truffle made with condensed milk and cocoa, often enjoyed at parties'),
	 (27,'Açaí Bowl 🥣🍇 – A frozen fruit bowl made with açaí berries, often topped with granola and honey'),
	 (27,'Moqueca 🍤🍛 – A Brazilian fish stew made with coconut milk, tomatoes, and spices'),
	 (27,'Churrasco 🥩🔥 – Brazilian BBQ, with skewered meats grilled over an open flam'),
	 (28,'Asado 🍖🔥 – Traditional Argentine BBQ with meats like beef, sausages, and rib');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (28,'Empanadas 🥟 – Pastry pockets filled with meat, cheese, or vegetables'),
	 (28,'Milanesa 🍽️🥩 – Breaded and fried meat cutlets, often served with mashed potatoes'),
	 (28,'Choripán 🌭🥖 – A sandwich made with Argentine sausage (chorizo) and chimichurri sauce'),
	 (28,'Dulce de Leche 🍯 – A sweet caramel-like spread, used in many Argentine desserts'),
	 (28,'Provoleta 🧀🔥 – Grilled cheese dish, typically served as part of the asado'),
	 (28,'Mate 🍵🌿 – Traditional herbal tea made from yerba mate leaves'),
	 (29,'Ceviche 🐟🍋 – Fresh raw fish marinated in lime juice, mixed with onions, chili, and cilantro'),
	 (29,'Lomo Saltado 🍖🍚 – A stir-fried beef dish with onions, tomatoes, and french fries, served with rice'),
	 (29,'Aji de Gallina 🍗🌶️ – A creamy chicken dish made with yellow chili and served with rice'),
	 (29,'Anticuchos 🍢 – Skewered grilled meat, often beef heart, served with potatoes');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (29,'Causa Rellena 🥔🥑 – A layered potato dish filled with chicken, tuna, or seafood, and avocado'),
	 (29,'Pisco Sour 🍸🍋 – A cocktail made with Pisco (a type of brandy), lemon juice, egg white, and bitters'),
	 (29,'Tamales 🌽🍖 – Corn dough filled with meat or vegetables, wrapped in leaves, and steamed'),
	 (30,'Pastel de Choclo 🌽🥧 – A corn pie made with ground beef, onions, and sweet corn topping'),
	 (30,'Empanadas de Pino 🥟 – Pastry pockets filled with a mixture of beef, onions, olives, and boiled egg'),
	 (30,'Curanto 🍖🔥 – A traditional dish made with meat, seafood, potatoes, and vegetables, cooked in a pit'),
	 (30,'Completo 🌭 – Chilean hot dog topped with avocado, tomato, mayonnaise, and sauerkraut'),
	 (30,'Mote con Huesillos 🍑🥤 – A sweet drink made from dried peaches and husked wheat'),
	 (30,'Cazuela 🍲 – A hearty stew made with chicken, beef, or pork, vegetables, and rice'),
	 (30,'Chilean Sea Bass 🐟🍽️ – A popular fish, often prepared with simple seasonings or in a casserole');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (31,'Meat Pie 🥧🥩 – A savory pastry filled with minced meat, gravy, mushrooms, and cheese'),
	 (31,'Vegemite 🍞 – A spread made from yeast extract, often enjoyed on toast with butter'),
	 (31,'Lamington 🍰🍫 – A sponge cake dipped in chocolate and rolled in desiccated coconut'),
	 (31,'Pavlova 🍰🍓 – A meringue dessert topped with whipped cream and fresh fruit'),
	 (31,'Anzac Biscuits 🍪 – Oat-based cookies traditionally made for ANZAC Day'),
	 (31,'Barramundi 🐟🍽️ – A popular Australian fish, often grilled or pan-fried'),
	 (31,'Tim Tams 🍫 – A beloved chocolate biscuit, often enjoyed with a hot drink'),
	 (32,'Hangi 🍗🔥 – Traditional Maori cooking where meat and vegetables are cooked in an underground oven'),
	 (32,'Pavlova 🍰🍓 – A meringue-based dessert, topped with cream and fruit, a Kiwi favorite'),
	 (32,'Meat Pies 🥧🥩 – Savory pies filled with minced meat, often eaten as a quick snack or lunch');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (32,'Kumara 🍠 – Sweet potato, often roasted or used in pies and soups'),
	 (32,'Fish and Chips 🐟🍟 – A classic takeaway meal of battered fish and fries'),
	 (32,'Whittaker`s Chocolate 🍫 – Renowned New Zealand chocolate, known for its smooth texture and flavors'),
	 (32,'Lamb 🐑🍖 – New Zealand is famous for its tender lamb, often roasted or grilled'),
	 (33,'Kokoda 🐟🍊 – A Fijian ceviche made with raw fish marinated in coconut milk and lime juice'),
	 (33,'Lovo 🍖🔥 – A traditional Fijian feast where meat and vegetables are cooked in an earth oven'),
	 (33,'Palusami 🍃🥥 – Taro leaves wrapped around coconut cream, often served with fish or meat'),
	 (33,'Fijian Curry 🍛 – A flavorful curry made with chicken, beef, or seafood, cooked in coconut milk'),
	 (33,'Rourou 🥥🍃 – Taro leaves cooked with coconut milk, a traditional Fijian dish'),
	 (33,'Fijian Pancakes 🥞 – Pancakes made from coconut milk and served with tropical fruit');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (33,'Fiji Water 💧 – Renowned for its purity, Fiji water is often considered a refreshing local beverage'),
	 (34,'Poi 🍠 – A staple in Hawaiian cuisine, poi is a smooth, sticky paste made from pounded taro root. It has a unique, slightly sour taste due to fermentation and is often enjoyed as a side dish'),
	 (34,'Kalua Pig 🐖 – Traditionally prepared by slow-cooking a whole pig in an underground oven called an imu, resulting in tender, smoky-flavored meat that`s a highlight at luaus'),
	 (34,'Lomi Lomi Salmon 🐟 – A refreshing salad made with salted diced salmon, tomatoes, onions, and sometimes chili peppers, offering a flavorful accompaniment to other dishes'),
	 (34,'Laulau 🌿 – A traditional dish where pork (sometimes combined with fish or chicken) is wrapped in taro leaves and steamed until tender, imparting a rich, earthy flavor'),
	 (34,'Poke 🍣 – A beloved Hawaiian dish featuring raw, marinated fish (commonly ahi tuna) cut into bite-sized pieces and seasoned with ingredients like soy sauce, seaweed, and sesame oil'),
	 (34,'Haupia 🍮 – A coconut milk-based dessert with a gelatin-like consistency, often served in small squares and enjoyed for its creamy, tropical flavor'),
	 (34,'Chicken Long Rice 🍜 – A dish influenced by Chinese cuisine, featuring clear mung bean noodles cooked with chicken, ginger, and garlic, resulting in a comforting soup-like meal'),
	 (35,'Poisson Cru 🐟🥥 – A raw fish salad marinated in coconut milk and lime juice, typically served with vegetables'),
	 (35,'Fafa 🌿🍖 – A dish made from taro leaves cooked in coconut milk, often served with chicken or fish');
INSERT INTO travel_db.cuisine (country_id,text) VALUES
	 (35,'Chevrettes 🍤 – Shrimp prepared in various ways, often grilled or served in a stew'),
	 (35,'Mahi Mahi 🐟🍽️ – A local fish, often grilled or served in curry'),
	 (35,'Poe 🍠🍰 – A sweet dessert made with mashed pumpkin, coconut milk, and sugar'),
	 (35,'Uru 🍞 – Breadfruit, often roasted or baked, and served with meats or fish'),
	 (35,'Taro 🌿🍠 – A versatile root vegetable, used in many dishes like soups and stews');
