INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (1,'24/7 Concierge Service – Personalized itineraries & reservations'),
	 (1,'Michelin-starred Dining – Experience gourmet cuisine at L’Espadon​'),
	 (1,'Ritz Club & Spa – Indoor pool, treatments by Biologique Recherche'),
	 (1,'Bar Hemingway – One of the most famous cocktail bars in the world'),
	 (1,'Pet-Friendly – Small pets allowed with VIP treatment'),
	 (2,'Two-Michelin-starred Restaurant – Led by Alain Ducasse'),
	 (2,'Le Dalí Restaurant – Artistic and casual dining​'),
	 (2,'Spa & Wellness – Treatments, sauna & relaxation spaces'),
	 (2,'Family-Friendly – Special amenities for children'),
	 (2,'Concierge Service – Personalized Paris experiences');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (3,'3 Michelin-starred Restaurants – Le Cinq, Le George & L’Orangerie'),
	 (3,'Spa & Wellness Center – Luxurious treatments & hammam'),
	 (3,'Indoor Pool & Fitness Studio – Relaxation with a view'),
	 (3,'24/7 Concierge – Customized plans & transportation'),
	 (3,'Pet-Friendly – Welcoming small pets on request'),
	 (4,'Michelin-starred Dining – Jean Imbert at Plaza Athénée​'),
	 (4,'Dior Spa – Exclusive beauty and wellness treatments'),
	 (4,'Elegant Cocktail Bar – Signature drinks in a chic setting'),
	 (4,'24/7 Concierge – VIP services & private transfers​'),
	 (4,'Pet-Friendly – Small pets welcomed with care');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (5,'​24/7 Concierge Service – Personalized plans & bookings'),
	 (5,'Michelin-starred Dining – Le Chantecler restaurant'),
	 (5,'Private Beach Access – With sun loungers & bar service'),
	 (5,'Art Collection – Over 6,000 pieces throughout the hotel'),
	 (5,'Fitness Room – Modern equipment for guests'),
	 (6,'Rooftop Dining – SEEN by Olivier restaurant & bar​'),
	 (6,'Spa & Wellness – Massages, sauna & Turkish bath'),
	 (6,'Fitness Center – Open daily for guests'),
	 (6,'24/7 Concierge – Tailored local recommendations'),
	 (6,'Event Spaces – Elegant rooms for weddings & business');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (7,'​Indoor & Outdoor Pools – Heated and sea-view'),
	 (7,'Restaurant Le 3e – Mediterranean cuisine'),
	 (7,'Sauna & Steam Room – Relaxing wellness zone'),
	 (7,'24/7 Concierge – Tours, reservations, transport'),
	 (7,'Fitness Studio – Equipped with cardio and weights'),
	 (8,'​Turkish Baths & Spa – Restorative rituals & therapies'),
	 (8,'Organic Restaurant – Farm-to-table Mediterranean dining'),
	 (8,'Monastic Garden – Olive trees, herbs, peaceful walking paths'),
	 (8,'Library & Salon – Cozy spaces for reading or tea'),
	 (8,'Concierge Service – Quiet luxury, tailored experiences');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (9,'​24/7 Concierge Service – Personalized itineraries & reservations'),
	 (9,'Rooftop Dining – Gourmet cuisine with city skyline views'),
	 (9,'Four Seasons Spa – Comprehensive wellness treatments'),
	 (9,'Indoor Pool – Heated pool with natural light'),
	 (9,'Fitness Center – Equipped with the latest technology'),
	 (10,'24/7 Concierge Service – Tailored experiences & bookings​'),
	 (10,'Michelin-Starred Dining – Exquisite culinary offerings'),
	 (10,'The Ritz Spa – Holistic wellness and beauty treatments'),
	 (10,'Indoor Pool – Elegant swimming area with relaxation zones'),
	 (10,'Fitness Suite – Personalized training programs');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (11,'24/7 Concierge Service – Customized cultural and leisure plans​'),
	 (11,'Lobbyto Restaurant – Innovative Spanish cuisine'),
	 (11,'Sisley Spa – Exclusive treatments and therapies'),
	 (11,'Library Lounge – Curated selection of classic literature'),
	 (11,'Fitness Center – Modern equipment for all fitness levels'),
	 (12,'​24/7 Concierge Service – Exclusive access to local attractions'),
	 (12,'Gourmet Dining – Multiple restaurants with diverse cuisines'),
	 (12,'Clarins Spa – Comprehensive wellness and beauty services'),
	 (12,'Rooftop Pool – Stunning views of Madrid`s skyline'),
	 (12,'Historic Gardens – Peaceful retreats within the hotel grounds');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (13,'24/7 Concierge Service – Personalized itineraries & reservations​'),
	 (13,'Michelin-Starred Dining – Exquisite culinary experiences'),
	 (13,'Spa & Wellness Center – Holistic treatments and therapies'),
	 (13,'Rooftop Pool – Panoramic city views'),
	 (13,'Fitness Center – State-of-the-art equipment'),
	 (14,'24/7 Concierge Service – Tailored experiences & bookings​'),
	 (14,'Two-Michelin-Starred Dining – Gourmet cuisine by renowned chefs'),
	 (14,'Spa & Wellness Center – Luxurious treatments and relaxation areas'),
	 (14,'Outdoor Pools – Overlooking the Mediterranean'),
	 (14,'Art Collection – Extensive contemporary pieces throughout the hotel');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (15,'24/7 Concierge Service – Personalized services and recommendations​'),
	 (15,'Gourmet Dining – Exquisite culinary offerings'),
	 (15,'Mayan-Inspired Spa – Unique treatments and therapies'),
	 (15,'Rooftop Garden – Lush greenery with city vistas'),
	 (15,'Fitness Center – Modern facilities for wellness'),
	 (16,'​24/7 Concierge Service – Customized experiences and bookings'),
	 (16,'Rooftop Bar – Trendy spot with panoramic views'),
	 (16,'Beachfront Pool – Relaxation with sea breezes'),
	 (16,'Full-Service Spa – Comprehensive wellness treatments'),
	 (16,'Fitness Center – Equipped for all workout needs');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (17,'24/7 Concierge Service – Personalized itineraries & reservations​'),
	 (17,'Le Jardin de Russie – Gourmet dining in a picturesque garden setting'),
	 (17,'De Russie Spa – Comprehensive wellness treatments'),
	 (17,'Stravinskij Bar – Renowned for its signature cocktails'),
	 (17,'Fitness Center – Equipped with modern facilities'),
	 (18,'​24/7 Concierge Service – Tailored experiences & bookings'),
	 (18,'La Terrazza – Michelin-starred restaurant with city views'),
	 (18,'Eden Spa – Holistic treatments and therapies'),
	 (18,'Rooftop Bar – Elegant setting for cocktails and relaxation'),
	 (18,'Fitness Center – State-of-the-art equipment');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (19,'24/7 Concierge Service – Customized cultural and leisure plans​'),
	 (19,'La Pergola – Three-Michelin-starred dining experience'),
	 (19,'Grand Spa – Extensive wellness and beauty treatments'),
	 (19,'Outdoor Pools – Surrounded by Mediterranean gardens'),
	 (19,'Art Collection – Featuring masterpieces and antiques'),
	 (20,'​24/7 Concierge Service – Personalized services and recommendations'),
	 (20,'J.K. Café – Offering Italian and international cuisine'),
	 (20,'Library Lounge – Curated selection of books and artworks'),
	 (20,'In-Room Spa Services – Tailored wellness treatments'),
	 (20,'Fitness Center – Modern facilities for wellness');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (21,'​24/7 Concierge Service – Personalized itineraries & reservations'),
	 (21,'La Veranda Restaurant – Gourmet Italian cuisine'),
	 (21,'Spa & Wellness Center – Holistic treatments and therapies'),
	 (21,'Indoor Pool – Set beneath a vaulted ceiling'),
	 (21,'Fitness Center – Equipped with modern facilities'),
	 (22,'​24/7 Concierge Service – Tailored experiences & bookings'),
	 (22,'Il Ristorante – Fine dining with innovative cuisine'),
	 (22,'Bvlgari Spa – Luxurious treatments and relaxation areas'),
	 (22,'Private Garden – A tranquil oasis in the city'),
	 (22,'Fitness Center – Featuring the latest equipment');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (23,'24/7 Concierge Service – Personalized services and recommendations​'),
	 (23,'Armani/Ristorante – Michelin-starred dining experience'),
	 (23,'Armani/SPA – Comprehensive wellness and beauty treatments'),
	 (23,'Rooftop Lounge – Stunning views of Milan`s skyline'),
	 (23,'Fitness Center – State-of-the-art facilities'),
	 (24,'24/7 Concierge Service – Customized cultural and leisure plans​'),
	 (24,'Gastronomic Restaurant – Exquisite culinary offerings'),
	 (24,'Grand Spa – Extensive wellness and beauty treatments'),
	 (24,'Private Garden – A serene escape within the city'),
	 (24,'Fitness Center – Equipped with modern amenities');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (25,'24/7 Concierge Service – Personalized itineraries & reservations​'),
	 (25,'Arva Restaurant – Seasonal Italian cuisine with canal views'),
	 (25,'Aman Spa – Tailored wellness treatments'),
	 (25,'Private Gardens – Tranquil spaces for relaxation'),
	 (25,'Exclusive Art Tours – Access to private collections and exhibitions'),
	 (26,'​24/7 Concierge Service – Tailored experiences & bookings'),
	 (26,'Oro Restaurant – Michelin-starred dining'),
	 (26,'Olympic-Sized Pool – Unique in central Venice'),
	 (26,'Casanova Wellness Centre – Comprehensive spa treatments'),
	 (26,'Private Shuttle – Complimentary boat service to central Venice');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (27,'24/7 Concierge Service – Personalized services and recommendations​'),
	 (27,'Club del Doge – Fine dining with canal views'),
	 (27,'The Gritti Spa – Luxurious treatments and therapies'),
	 (27,'Epicurean School – Hands-on Venetian cooking classes'),
	 (27,'Rooftop Terrace – Panoramic views of Venice'),
	 (28,'​24/7 Concierge Service – Personalized itineraries & reservations'),
	 (28,'L’Alcova Restaurant – Traditional Italian cuisine with Grand Canal views'),
	 (28,'Seasonal Rooftop Terrace – Panoramic vistas of Venice'),
	 (28,'Cooking Classes – Learn regional delicacies with the executive chef'),
	 (28,'Historic Interiors – Original frescoes, Murano glass, and antique furnishings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (29,'​24/7 Concierge Service – Personalized itineraries & reservations'),
	 (29,'The Ritz Restaurant – Michelin-starred dining experience'),
	 (29,'Afternoon Tea – Served in the opulent Palm Court'),
	 (29,'The Ritz Club – Exclusive gaming and entertainment venue'),
	 (29,'Chauffeur Service – Luxury car transfers available'),
	 (30,'24/7 Concierge Service – Tailored experiences & bookings​'),
	 (30,'Claridge`s Restaurant – Modern British cuisine'),
	 (30,'Claridge`s Spa – Holistic treatments and wellness programs'),
	 (30,'The Fumoir – Intimate cocktail bar with vintage charm'),
	 (30,'Afternoon Tea – A celebrated tradition in the Foyer & Reading Room');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (31,'24/7 Concierge Service – Customized cultural and leisure plans​'),
	 (31,'Gordon Ramsay’s Savoy Grill – Classic British dishes with a modern twist'),
	 (31,'American Bar – One of the world`s oldest surviving cocktail bars'),
	 (31,'Beauty & Fitness – Gym, indoor pool, and spa treatments'),
	 (31,'Theatre Desk – Exclusive access to West End shows and events'),
	 (32,'​24/7 Concierge Service – Personalized services and recommendations'),
	 (32,'Hélène Darroze at The Connaught – Three-Michelin-starred dining'),
	 (32,'The Connaught Bar – Award-winning cocktails in an art deco setting'),
	 (32,'Aman Spa – Exclusive treatments and wellness programs'),
	 (32,'Art Collection – Curated pieces throughout the hotel');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (33,'24/7 Concierge Service – Personalized itineraries & reservations​'),
	 (33,'Number One Restaurant – Michelin-starred dining experience'),
	 (33,'Afternoon Tea – Served in the opulent Palm Court'),
	 (33,'The Balmoral Spa – Exclusive treatments and wellness programs'),
	 (33,'Chauffeur Service – Luxury car transfers available'),
	 (34,'​24/7 Concierge Service – Tailored experiences & bookings'),
	 (34,'Grazing by Mark Greenaway – Modern Scottish cuisine'),
	 (34,'Guerlain Spa – Holistic treatments and wellness programs'),
	 (34,'Peacock Alley – Intimate cocktail bar with vintage charm'),
	 (34,'Afternoon Tea – A celebrated tradition in the Peacock Alley');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (35,'24/7 Concierge Service – Customized cultural and leisure plans​'),
	 (35,'The Witchery Restaurant – Classic Scottish dishes with a modern twist'),
	 (35,'Unique Suites – Individually designed with antique furnishings'),
	 (35,'In-Room Dining – Gourmet meals served in the privacy of your suite'),
	 (35,'Theatre Desk – Exclusive access to local shows and events'),
	 (36,'24/7 Concierge Service – Personalized services and recommendations​'),
	 (36,'Rhubarb Restaurant – Fine dining with local ingredients'),
	 (36,'Private Dining Rooms – Exclusive spaces for special occasions'),
	 (36,'Afternoon Tea – Served in the opulent drawing rooms'),
	 (36,'Chauffeur Service – Luxury car transfers available');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (37,'24/7 Concierge Service – Personalized itineraries & reservations​'),
	 (37,'Dstrikt Steakhouse – Premium cuts and local produce'),
	 (37,'The Ritz-Carlton Spa – Indoor pool, sauna, and treatments'),
	 (37,'Atmosphere Rooftop Bar – Cocktails with city skyline views'),
	 (37,'Club Lounge – Exclusive access with culinary offerings'),
	 (38,'​24/7 Concierge Service – Tailored experiences & bookings'),
	 (38,'Restaurant Rote Bar – Traditional Austrian cuisine'),
	 (38,'Café Sacher – Home of the original Sachertorte'),
	 (38,'Sacher Spa – Signature treatments and wellness programs'),
	 (38,'Boutique Shopping – Exclusive in-house stores');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (39,'24/7 Concierge Service – Customized cultural and leisure plans​'),
	 (39,'The Bank Brasserie & Bar – Contemporary European cuisine'),
	 (39,'Arany Spa – Indoor pool, sauna, and wellness treatments'),
	 (39,'Fitness Centre – State-of-the-art equipment'),
	 (39,'Meeting & Event Spaces – Elegant venues for all occasions'),
	 (40,'​24/7 Concierge Service – Personalized services and recommendations'),
	 (40,'Restaurant Opus – Gourmet dining with seasonal menus'),
	 (40,'Café Imperial Wien – Traditional Viennese coffeehouse'),
	 (40,'Imperial Spa – Luxurious treatments and fitness facilities'),
	 (40,'Butler Service – Available in select suites for added luxury');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (41,'24/7 Concierge Service – Personalized itineraries & reservations​'),
	 (41,'Gourmet Restaurant – Traditional Austrian cuisine'),
	 (41,'Café Sacher – Home of the original Sacher-Torte'),
	 (41,'Sacher Spa – Exclusive treatments and wellness programs'),
	 (41,'Chauffeur Service – Luxury car transfers available'),
	 (42,'​24/7 Concierge Service – Tailored experiences & bookings'),
	 (42,'Heritage Restaurant – Modern Austrian cuisine'),
	 (42,'Historic Interiors – Antique furnishings and artwork'),
	 (42,'Boutique Shopping – Exclusive in-house stores'),
	 (42,'Afternoon Tea – A celebrated tradition in the lounge');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (43,'​24/7 Concierge Service – Customized cultural and leisure plans'),
	 (43,'Polo Lounge – Classic European dishes with a modern twist'),
	 (43,'Crystal Bar – One of the city`s most elegant cocktail bars'),
	 (43,'Art Collection – Curated pieces throughout the hotel'),
	 (43,'Theatre Desk – Exclusive access to local shows and events'),
	 (44,'24/7 Concierge Service – Personalized services and recommendations​'),
	 (44,'The Glass Garden – Michelin-starred dining with panoramic views'),
	 (44,'Mönchstein Spa – Exclusive treatments and wellness programs'),
	 (44,'Infinity Pool – Overlooking the city skyline'),
	 (44,'Private Park – Tranquil gardens for relaxation');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (45,'​24/7 Concierge Service – Tailored experiences & VIP access'),
	 (45,'Rooftop Bar – Panoramic views & signature cocktails'),
	 (45,'Sense Spa – Stainless steel pool, hammam & treatments'),
	 (45,'Mediterranean Restaurant – Elegant dining on-site'),
	 (45,'Tech Gym – State-of-the-art equipment'),
	 (46,'​24/7 Concierge Service – Cultural tours & reservations'),
	 (46,'Floret Restaurant & Bar – Stylish cuisine & drinks'),
	 (46,'Wellness Centre – Sauna, treatments & fitness studio'),
	 (46,'Executive Lounge – Private space for premium guests'),
	 (46,'Event Spaces – Elegant venues for all occasions');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (47,'​24/7 Concierge Service – Premium local recommendations'),
	 (47,'Millennium Spa & Wellness – Panoramic spa & treatments'),
	 (47,'10 Dining Venues – From fine dining to rooftop lounges'),
	 (47,'Sky Lounge – Breathtaking skyline cocktails'),
	 (47,'Smart Rooms – With touch control systems'),
	 (48,'24/7 Concierge Service – Personalized travel arrangements​'),
	 (48,'The Revolutionary Dining Room – Modern cuisine in luxe style'),
	 (48,'Vaya Spa – Signature treatments, sauna & steam rooms'),
	 (48,'Rooftop Bar – Vitosha Mountain views & cocktails'),
	 (48,'Regency Club – Exclusive lounge access');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (49,'24/7 Concierge Service – Personalized assistance and recommendations​'),
	 (49,'Gourmet Restaurant – Fine dining with a selection of international dishes'),
	 (49,'Rooftop Terrace – Panoramic views of Varna city'),
	 (49,'Wellness Center – Sauna, fitness facilities, and massage services'),
	 (49,'Art Gallery – Showcasing contemporary Bulgarian artists'),
	 (50,'24/7 Concierge Service – Assistance with tours and reservations​'),
	 (50,'Elegant Restaurant – Serving Bulgarian and European cuisine'),
	 (50,'Classic Bar – Offering a wide selection of drinks in a vintage setting'),
	 (50,'Business Center – Equipped for meetings and conferences'),
	 (50,'Fitness Room – Available for guest use');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (51,'​24/7 Concierge Service – Tailored recommendations and bookings'),
	 (51,'Bistro Restaurant – Offering a variety of local and international dishes'),
	 (51,'Fitness Center – Modern equipment for guest use'),
	 (51,'Complimentary Bicycles – For exploring Varna'),
	 (51,'Library Lounge – A quiet space for reading and relaxation'),
	 (52,'​24/7 Concierge Service – Personalized services and local insights'),
	 (52,'Outdoor Pool – Seasonal swimming pool with sun loungers'),
	 (52,'Spa Center – Sauna, hot tub, and massage treatments'),
	 (52,'Garden Area – Beautifully landscaped grounds for relaxation'),
	 (52,'Tennis Court – Available for guest use');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (53,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (53,'Michelin-Starred Dining – Exquisite culinary experiences'),
	 (53,'Nordic Spa & Fitness Club – Comprehensive wellness facilities'),
	 (53,'Waterfront Views – Stunning vistas of Stockholm`s harbor'),
	 (53,'Event Spaces – Elegant venues for meetings and celebrations'),
	 (54,'24/7 Concierge Service – Tailored experiences and bookings​'),
	 (54,'T/BAR Restaurant – Contemporary cuisine with a Scandinavian twist'),
	 (54,'Wellness Area – Sauna, gym, and massage treatments'),
	 (54,'Art Collection – Curated pieces throughout the hotel'),
	 (54,'Business Facilities – Meeting rooms and event spaces');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (55,'​24/7 Concierge Service – Personalized services and recommendations'),
	 (55,'NOI Restaurant – Innovative dishes in a stylish setting'),
	 (55,'Fitness Center – State-of-the-art equipment'),
	 (55,'Lounge Bar – Elegant space for cocktails and relaxation'),
	 (55,'Meeting Rooms – Equipped for business events'),
	 (56,'24/7 Concierge Service – Customized itineraries and reservations​'),
	 (56,'Lydmar Restaurant – Seasonal menus with local ingredients'),
	 (56,'Terrace – Outdoor seating with waterfront views'),
	 (56,'Art Exhibitions – Regular showcases of contemporary artists'),
	 (56,'Live Music – Weekly performances in the lounge');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (57,'​24/7 Concierge Service – Personalized services and local experiences'),
	 (57,'Spa Rituals – Unique Nordic spa experiences with pools, saunas, and treatments'),
	 (57,'Award-Winning Golf – 18-hole course in scenic surroundings'),
	 (57,'Health Club – Fitness center, yoga, and training classes'),
	 (57,'Fine Dining – Multiple restaurants with seasonal, local cuisine'),
	 (58,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (58,'Atelier Restaurant – Seasonal menus with local ingredients'),
	 (58,'Suite Belle – Features a wine cellar, designer fashion items, and in-room bar service'),
	 (58,'Artful Decor – Rich colors and vintage furnishings throughout'),
	 (58,'Central Location – Close to shopping, dining, and cultural sites');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (59,'​24/7 Concierge Service – Personalized services and recommendations'),
	 (59,'Upper House Dining – Gourmet restaurant with innovative cuisine'),
	 (59,'Spa & Wellness – Includes an outdoor glass-bottom pool, sauna, and treatments'),
	 (59,'Luxurious Rooms – Spacious accommodations with contemporary design'),
	 (59,'Prime Location – Adjacent to Liseberg amusement park and the Swedish Exhibition & Congress Centre'),
	 (60,'24/7 Concierge Service – Assistance with tours and reservations​'),
	 (60,'Seasonal Restaurant – Focused on organic and locally sourced ingredients'),
	 (60,'Rooftop Pool – Heated pool with city views (seasonal)'),
	 (60,'Artistic Decor – Features contemporary art installations'),
	 (60,'Central Location – Walking distance to major attractions and shopping districts');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (61,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (61,'Iridium Spa – Comprehensive wellness facilities'),
	 (61,'Multiple Fine Dining Options – Exquisite culinary experiences'),
	 (61,'Panoramic Nile Views – Stunning vistas of the river'),
	 (61,'Event Spaces – Elegant venues for meetings and celebrations'),
	 (62,'24/7 Concierge Service – Tailored experiences and bookings​'),
	 (62,'Spa and Wellness Center – Sauna, gym, and massage treatments'),
	 (62,'Multiple Restaurants – Offering international and local cuisines'),
	 (62,'Outdoor Pools – For relaxation and leisure'),
	 (62,'Business Facilities – Meeting rooms and event spaces');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (63,'​24/7 Concierge Service – Customized itineraries and reservations'),
	 (63,'Outdoor Pool – Surrounded by greenery'),
	 (63,'Multiple Dining Options – Serving international and local dishes'),
	 (63,'Historic Architecture – Reflecting Egypt`s rich heritage'),
	 (63,'Event Spaces – Ideal for weddings and conferences'),
	 (64,'​24/7 Concierge Service – Assistance with tours and reservations'),
	 (64,'Infinity Pool – Overlooking the Nile'),
	 (64,'Multiple Restaurants – Including French, Moroccan, and Asian cuisines'),
	 (64,'Spa and Fitness Center – For relaxation and wellness'),
	 (64,'Cultural Proximity – Close to museums and historic sites');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (65,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (65,'Private Beach – Exclusive access to the Mediterranean Sea'),
	 (65,'Multiple Fine Dining Options – Including Lebanese and Italian cuisines'),
	 (65,'Spa and Wellness Center – Comprehensive wellness facilities'),
	 (65,'Infinity Pool – Overlooking the sea'),
	 (66,'​24/7 Concierge Service – Custom bookings and city tours'),
	 (66,'French Restaurant – Fine dining in a historic ambiance'),
	 (66,'Sea View Rooms – Private balconies with Corniche views'),
	 (66,'Business Center – Meeting rooms and conference services'),
	 (66,'Elegant Lounge Bar – For cocktails and social evenings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (67,'24/7 Concierge Service – VIP treatment and local guidance​'),
	 (67,'Outdoor Pool – With garden and partial sea views'),
	 (67,'Private Beach Access – Calm, clean, and exclusive'),
	 (67,'Mediterranean Dining – Fresh seafood and international favorites'),
	 (67,'Fitness & Wellness Zone – Gym, sauna, and massage on request'),
	 (68,'​24/7 Concierge Service – Personalized assistance anytime'),
	 (68,'Rooftop Terrace – Breakfast with panoramic sea views'),
	 (68,'Classic Rooms – Hand-decorated ceilings & vintage ambiance'),
	 (68,'Central Location – Walkable to cultural and coastal landmarks'),
	 (68,'Elegant Lobby Lounge – Ideal for evening drinks or tea');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (69,'24/7 Concierge Service – Personalized itineraries and local experiences​'),
	 (69,'Private Beach Access – Sunbeds, beach bar, and ocean serenity'),
	 (69,'Le Spa – Hammam, luxury facials, and ocean-view relaxation rooms'),
	 (69,'Infinity Pool – Heated, surrounded by palm trees and loungers'),
	 (69,'Gourmet Restaurants – Mediterranean and Moroccan fine dining'),
	 (70,'24/7 Concierge Service – Tailored cultural tours and reservations​'),
	 (70,'Spa & Wellness Center – Hammam rituals, beauty salon, and gym'),
	 (70,'Sky-high Dining – Rooftop bars and restaurants with city views'),
	 (70,'Business Lounge – For corporate meetings and premium services'),
	 (70,'Cultural Proximity – Walk to Hassan II Mosque and Old Medina');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (71,'24/7 Concierge Service – From restaurant bookings to private tours​'),
	 (71,'Outdoor Pool – Tranquil garden setting with poolside service'),
	 (71,'Spa & Wellness Center – Traditional hammam and massage rooms'),
	 (71,'World-Class Dining – Moroccan, French, and international cuisine'),
	 (71,'Fitness Center – Fully equipped gym for active guests'),
	 (72,'24/7 Concierge Service – VIP services, transport & reservations​'),
	 (72,'Indoor Heated Pool – Perfect for all-season relaxation'),
	 (72,'O-Spa by Clarins – Full-service treatments and hammam'),
	 (72,'Skyline Dining – Spectacular city views from top-floor restaurants'),
	 (72,'Executive Lounge – For business travelers and private meetings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (73,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (73,'Private Riads – Each with a courtyard, rooftop terrace, and plunge pool'),
	 (73,'Spa & Wellness Center – Hammam, massages, facials, and fitness'),
	 (73,'Gourmet Restaurants – Moroccan and international fine dining'),
	 (73,'Lush Gardens – Tranquil spaces with fountains and shaded walkways'),
	 (74,'​24/7 Concierge Service – Custom bookings and city tours'),
	 (74,'Spa & Wellness Center – Hammam, sauna, beauty treatments, and fitness center'),
	 (74,'Outdoor Pool – Surrounded by lush gardens'),
	 (74,'Fine Dining – Multiple restaurants offering diverse cuisines'),
	 (74,'Elegant Lounge Bar – For cocktails and social evenings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (75,'24/7 Concierge Service – Personalized assistance and recommendations​'),
	 (75,'Private Villas – Each with a pool and garden'),
	 (75,'Spa & Wellness Center – Ayurvedic treatments, hammam, and yoga sessions'),
	 (75,'Gourmet Restaurants – Moroccan and international cuisines'),
	 (75,'Outdoor Pool – Overlooking the Atlas Mountains'),
	 (76,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (76,'Spacious Pavilions – Each with a private garden and some with pools'),
	 (76,'Spa & Wellness Center – Hammam, massages, and beauty treatments'),
	 (76,'Fine Dining – Moroccan and Mediterranean cuisines'),
	 (76,'Outdoor Pool – Surrounded by olive groves and palm trees');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (77,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (77,'Private Villas – Each with a courtyard and plunge pool'),
	 (77,'Spa & Wellness Center – Hammam, massages, facials, and fitness'),
	 (77,'Gourmet Restaurants – South African and international fine dining'),
	 (77,'Lush Gardens – Tranquil spaces with fountains and shaded walkways'),
	 (78,'​24/7 Concierge Service – Custom bookings and city tours'),
	 (78,'Spa & Wellness Center – Hammam, sauna, beauty treatments, and fitness center'),
	 (78,'Outdoor Pool – Surrounded by lush gardens'),
	 (78,'Fine Dining – Multiple restaurants offering diverse cuisines'),
	 (78,'Elegant Lounge Bar – For cocktails and social evenings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (79,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (79,'Indoor Pool – Perfect for all-season relaxation'),
	 (79,'Spa & Wellness Center – Comprehensive wellness facilities'),
	 (79,'Fine Dining – Italian and international cuisines'),
	 (79,'Business Facilities – Meeting rooms and conference services'),
	 (80,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (80,'Outdoor Pool – Set amidst lush gardens'),
	 (80,'Gourmet Restaurant – Seasonal menus with local ingredients'),
	 (80,'Fitness Center – Fully equipped gym for guests'),
	 (80,'Eco-Friendly Initiatives – Sustainable practices throughout the property');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (81,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (81,'Spa & Wellness Center – Treatments on a private island'),
	 (81,'Outdoor Infinity Pool – With panoramic mountain views'),
	 (81,'Gourmet Restaurants – Including Nobu and Ochre'),
	 (81,'KidsOnly Club – Engaging activities for younger guests'),
	 (82,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (82,'Rooftop Pool – Overlooking the city and Table Mountain'),
	 (82,'Spa & Wellness Center – Personalized treatments'),
	 (82,'Fine Dining – Seasonal menus with local ingredients'),
	 (82,'Art Gallery – Featuring contemporary African art');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (83,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (83,'Art Gallery – Showcasing South African artworks'),
	 (83,'Wine Gallery – Featuring a curated selection of local wines'),
	 (83,'Spa & Wellness Center – Comprehensive wellness facilities'),
	 (83,'Outdoor Pool – With ocean views'),
	 (84,'​24/7 Concierge Service – Custom bookings and city tours'),
	 (84,'Spa & Wellness Center – Hammam, sauna, beauty treatments, and fitness center'),
	 (84,'Outdoor Pool – Surrounded by lush gardens'),
	 (84,'Fine Dining – Multiple restaurants offering diverse cuisines'),
	 (84,'Elegant Lounge Bar – For cocktails and social evenings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (85,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (85,'Spa & Wellness Center – Comprehensive wellness facilities'),
	 (85,'Rooftop Pool – With panoramic city views'),
	 (85,'Gourmet Restaurants – Offering diverse cuisines'),
	 (85,'Fitness Center – Fully equipped gym for guests'),
	 (86,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (86,'Spa & Wellness Center – Personalized treatments'),
	 (86,'Fine Dining – Seasonal menus with local ingredients'),
	 (86,'Outdoor Pool – Surrounded by lush gardens'),
	 (86,'Elegant Lounge Bar – For cocktails and social evenings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (87,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (87,'Unique Wildlife Experience – Interactions with resident giraffes'),
	 (87,'Fine Dining – Gourmet meals with local ingredients'),
	 (87,'Elegant Lounge – For relaxation and socializing'),
	 (87,'Beautiful Gardens – Tranquil spaces with indigenous flora'),
	 (88,'24/7 Concierge Service – Custom bookings and city tours​'),
	 (88,'Spa & Wellness Center – Hammam, sauna, beauty treatments, and fitness center'),
	 (88,'Outdoor Pool – Surrounded by lush gardens'),
	 (88,'Fine Dining – Multiple restaurants offering diverse cuisines'),
	 (88,'Elegant Lounge Bar – For cocktails and social evenings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (89,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (89,'Spa & Wellness Center – Treatments inspired by local traditions'),
	 (89,'Outdoor Pool – With panoramic savanna views'),
	 (89,'Gourmet Restaurant – Offering locally sourced cuisine'),
	 (89,'Wildlife Experiences – Guided safaris and animal tracking'),
	 (90,'24/7 Concierge Service – Tailored experiences and bookings​'),
	 (90,'Outdoor Pool – Surrounded by lush gardens'),
	 (90,'Fine Dining – Gourmet restaurant with city views'),
	 (90,'Wine Cellar – Featuring a curated selection of local wines'),
	 (90,'Elegant Lounge – For relaxation and socializing');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (91,'24/7 Concierge Service – Personalized assistance and recommendations​'),
	 (91,'Outdoor Pool – With panoramic city views'),
	 (91,'Fine Dining – Multiple restaurants offering diverse cuisines'),
	 (91,'Wine Cellar – Featuring a curated selection of local wines'),
	 (91,'Elegant Lounge – For cocktails and social evenings'),
	 (92,'​24/7 Concierge Service – Custom bookings and city tours'),
	 (92,'Spa & Wellness Center – Hammam, sauna, beauty treatments, and fitness center'),
	 (92,'Outdoor Pool – Surrounded by lush gardens'),
	 (92,'Fine Dining – Multiple restaurants offering diverse cuisines'),
	 (92,'Elegant Lounge Bar – For cocktails and social evenings');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (93,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (93,'Spa & Wellness Center – Comprehensive wellness facilities'),
	 (93,'Outdoor Pool – With panoramic marina views'),
	 (93,'Gourmet Restaurant – Offering locally sourced cuisine'),
	 (93,'Fitness Center – Fully equipped gym for guests'),
	 (94,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (94,'Spa & Wellness Center – Personalized treatments'),
	 (94,'Infinity Pool – Overlooking the Indian Ocean'),
	 (94,'Fine Dining – Seasonal menus with local ingredients'),
	 (94,'Private Villas – With ocean-facing decks');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (95,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (95,'Outdoor Terrace – With panoramic city views'),
	 (95,'Breakfast Service – Featuring local and international options'),
	 (95,'Airport Shuttle – Available upon request'),
	 (95,'Free Wi-Fi – Throughout the property'),
	 (96,'24/7 Concierge Service – Custom bookings and island tours​'),
	 (96,'Spa & Wellness Center – Hammam, sauna, beauty treatments, and fitness center'),
	 (96,'Outdoor Pool – Overlooking the beach'),
	 (96,'Fine Dining – Featuring Creole and international dishes'),
	 (96,'Beach Access – Directly from the hotel grounds');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (97,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (97,'Spa & Wellness Center – Comprehensive wellness facilities'),
	 (97,'Outdoor Pool – With panoramic ocean views'),
	 (97,'Gourmet Restaurants – Offering international and Creole cuisine'),
	 (97,'Fitness Center – Fully equipped gym for guests'),
	 (98,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (98,'Spa & Wellness Center – Personalized treatments'),
	 (98,'Outdoor Pool – Surrounded by lush gardens'),
	 (98,'Diverse Dining Options – From gourmet to casual eateries'),
	 (98,'Water Sports Center – Equipment and guided activities');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (99,'​24/7 Concierge Service – Custom bookings and island tours'),
	 (99,'Spa & Wellness Center – Hammam, sauna, beauty treatments, and fitness center'),
	 (99,'Infinity Pool – Overlooking the ocean'),
	 (99,'Fine Dining – Featuring Creole and international dishes'),
	 (99,'Beach Access – Directly from the hotel grounds'),
	 (100,'​24/7 Concierge Service – Assistance with tours and reservations'),
	 (100,'Outdoor Pool – With sun loungers and ocean views'),
	 (100,'Multiple Restaurants – Including international and local cuisine'),
	 (100,'Water Sports Facilities – Equipment rental and lessons'),
	 (100,'Free Wi-Fi – Throughout the property');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (101,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (101,'La Prairie Spa – Comprehensive wellness treatments'),
	 (101,'Rooftop Pool – With panoramic city views'),
	 (101,'Jean-Georges Beverly Hills – Gourmet dining experience'),
	 (101,'Fitness Center – State-of-the-art equipment'),
	 (102,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (102,'Spa & Wellness Center – Personalized treatments'),
	 (102,'Outdoor Pool – Surrounded by lush gardens'),
	 (102,'Wolfgang Puck at Hotel Bel-Air – Fine dining'),
	 (102,'Complimentary Car Service – Within a 3-mile radius');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (103,'24/7 Concierge Service – Custom bookings and arrangements​'),
	 (103,'Spa by La Prairie – Exclusive treatments'),
	 (103,'Iconic Pool – With private cabanas'),
	 (103,'Polo Lounge – Historic dining venue'),
	 (103,'Fitness Center – Fully equipped gym'),
	 (104,'​24/7 Concierge Service – Personalized assistance and recommendations'),
	 (104,'Rooftop Pool – With city skyline views'),
	 (104,'Multiple Restaurants – Offering diverse culinary experiences'),
	 (104,'Fitness Center – State-of-the-art facilities'),
	 (104,'Event Spaces – For meetings and special occasions');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (105,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (105,'Rooftop Bar – Offering panoramic city views'),
	 (105,'Spa & Wellness Center – Comprehensive wellness treatments'),
	 (105,'Fine Dining – Featuring locally sourced cuisine'),
	 (105,'Fitness Center – State-of-the-art equipment'),
	 (106,'24/7 Concierge Service – Tailored experiences and bookings​'),
	 (106,'Spa & Wellness Center – Personalized treatments'),
	 (106,'The Palm Court – Iconic venue for afternoon tea'),
	 (106,'Butler Service – Available in select suites'),
	 (106,'Fitness Center – Fully equipped gym');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (107,'24/7 Concierge Service – Custom bookings and arrangements​'),
	 (107,'Spa & Wellness Center – Exclusive treatments'),
	 (107,'Indoor Lap Pool – Heated and ideal for relaxation'),
	 (107,'Wolfgang Puck’s CUT – Fine dining steakhouse'),
	 (107,'Fitness Center – State-of-the-art facilities'),
	 (108,'24/7 Concierge Service – Personalized assistance and recommendations​'),
	 (108,'Butler Service – Signature St. Regis offering'),
	 (108,'King Cole Bar – Home of the original Bloody Mary'),
	 (108,'Afternoon Tea – Traditional service in a luxurious setting'),
	 (108,'Fitness Center – Modern equipment and facilities');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (109,'​24/7 Concierge Service – Personalized itineraries and reservations'),
	 (109,'The Spa at Wynn – Comprehensive wellness treatments'),
	 (109,'Multiple Fine Dining Restaurants – Including SW Steakhouse and Mizumi'),
	 (109,'Wynn Golf Club – Championship 18-hole course'),
	 (109,'Luxury Shopping – Featuring brands like Dior, Chanel, and Louis Vuitton'),
	 (110,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (110,'Gondola Rides – Romantic journeys along the Grand Canal'),
	 (110,'Canyon Ranch Spa – Extensive wellness and fitness offerings'),
	 (110,'Grand Canal Shoppes – Over 160 luxury boutiques'),
	 (110,'Multiple Pools – Including the Venetian Pool Deck with cabanas');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (111,'​24/7 Concierge Service – Custom bookings and arrangements'),
	 (111,'Smart Rooms – Automated lighting, temperature, and curtains'),
	 (111,'The Spa & Salon at ARIA – Comprehensive wellness treatments'),
	 (111,'Multiple Pools – Including a Sky Pool for Sky Suite guests'),
	 (111,'Fine Dining – Restaurants by chefs like Jean Georges and Julian Serrano'),
	 (112,'24/7 Concierge Service – Personalized assistance and recommendations​'),
	 (112,'Private Pool – Exclusive to Four Seasons guests'),
	 (112,'Veranda Restaurant – Offering indoor and outdoor dining'),
	 (112,'Full-Service Spa – A range of treatments and therapies'),
	 (112,'Direct Access – To Mandalay Bay`s casino and entertainment options');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (113,'24/7 Concierge Service – Personalized itineraries and reservations​'),
	 (113,'Spa – Comprehensive wellness treatments'),
	 (113,'Café Boulud – French-inspired cuisine'),
	 (113,'Indoor Pool – Heated and ideal for relaxation'),
	 (113,'Fitness Center – State-of-the-art equipment'),
	 (114,'​24/7 Concierge Service – Tailored experiences and bookings'),
	 (114,'Spa – Personalized treatments'),
	 (114,'TOCA Restaurant – Italian-inspired dining'),
	 (114,'Club Lounge – Exclusive access with additional amenities'),
	 (114,'Fitness Center – Fully equipped gym');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (115,'24/7 Concierge Service – Custom bookings and arrangements​'),
	 (115,'Spa by Valmont – Exclusive treatments'),
	 (115,'ONE Restaurant – Gourmet dining experience'),
	 (115,'Private Screening Room – For intimate viewings'),
	 (115,'Fitness Center – Modern equipment and facilities'),
	 (116,'24/7 Concierge Service – Personalized assistance and recommendations​'),
	 (116,'Miraj Hammam Spa – Traditional treatments'),
	 (116,'Bosk Restaurant – Asian-inspired cuisine'),
	 (116,'Lobby Lounge – Live music and afternoon tea'),
	 (116,'Fitness Center – Advanced equipment in a peaceful setting');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (117,'24-hour concierge service – Personalized assistance for your every need​'),
	 (117,'Rooftop pool – Breathtaking panoramic views of the harbor and mountains'),
	 (117,'Willow Stream Spa – A tranquil retreat offering traditional treatments'),
	 (117,'Botanist Restaurant – Contemporary cuisine inspired by local ingredients'),
	 (117,'Fitness center – State-of-the-art equipment for all fitness levels'),
	 (118,'24-hour concierge service – Personalized recommendations and assistance​'),
	 (118,'Sense spa – Luxurious treatments and serene atmosphere'),
	 (118,'Hawksworth Restaurant – Award-winning Canadian cuisine'),
	 (118,'Saltwater indoor pool – Relaxing swim experience'),
	 (118,'Pet-friendly – Welcoming your furry companions with luxury amenities');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (119,'24/7 concierge service – Personalized assistance and recommendations​'),
	 (119,'Miraj Hammam Spa – Traditional Middle Eastern-inspired treatments'),
	 (119,'Bosk Restaurant – Asian-inspired fine dining'),
	 (119,'Lobby Lounge – Live music and afternoon tea service'),
	 (119,'Fitness center – Advanced equipment in a peaceful setting'),
	 (120,'​24-hour concierge service – Tailored recommendations and bookings'),
	 (120,'Bacchus Restaurant – Classic French-inspired cuisine'),
	 (120,'The Spa at Wedgewood – Signature treatments for relaxation'),
	 (120,'Afternoon tea – A quintessentially British experience'),
	 (120,'Fitness center – Fully equipped for a balanced lifestyle');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (121,'24-hour concierge service – Personalized assistance for all your needs​'),
	 (121,'La Terraza – Beautiful outdoor pool surrounded by gardens'),
	 (121,'Pan Dulce Restaurant – Fine dining with Mexican and international flavors'),
	 (121,'Fitness center – State-of-the-art equipment and classes'),
	 (121,'Spa – Offering a range of rejuvenating treatments'),
	 (122,'​24-hour butler service – Personal assistance at your convenience'),
	 (122,'J&G Grill – Contemporary dining with international flavors'),
	 (122,'King Cole Bar – Known for its classic cocktails and vibrant atmosphere'),
	 (122,'Remède Spa – Rejuvenating treatments and services'),
	 (122,'Indoor pool – Relaxing space with city views');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (123,'​24-hour concierge service – Tailored recommendations and bookings'),
	 (123,'Anatol Restaurant – Contemporary Mexican cuisine with international influences'),
	 (123,'Aura Spa – Signature treatments with organic products'),
	 (123,'Fitness center – Cutting-edge equipment and wellness services'),
	 (123,'In-room dining – Personalized gourmet experiences'),
	 (124,'24-hour concierge service – Exceptional personalized attention​'),
	 (124,'Grill Ritz – Exquisite dining with local and international flavors'),
	 (124,'The Ritz-Carlton Spa – Award-winning wellness treatments'),
	 (124,'Rooftop bar – Stunning views of the city and Chapultepec Park'),
	 (124,'Fitness center – A complete range of exercise equipment');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (125,'​Private beach – White sand and crystal-clear Caribbean waters'),
	 (125,'ESPA Spa – Award-winning treatments and hydrotherapy rituals'),
	 (125,'Six gourmet restaurants – Global cuisine from Asian to Mexican'),
	 (125,'Infinity pools – Overlooking the sea, adults-only and family options'),
	 (125,'Butler service – Personalized attention in luxury suites'),
	 (126,'Butler service – Attentive and discreet, available 24/7​'),
	 (126,'BlancSpa – Holistic and hydrotherapy experiences'),
	 (126,'Fine dining – French, Italian, Asian, and more with à la carte menus'),
	 (126,'Infinity pools – Multiple beachfront pools with stunning views'),
	 (126,'Wellness center – Yoga, Pilates, and a state-of-the-art gym');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (127,'Infinity pool – Panoramic views over the city skyline​'),
	 (127,'Spa InterContinental – Personalized massages and beauty treatments'),
	 (127,'Fine dining – Three upscale restaurants offering global cuisine'),
	 (127,'24-hour fitness center – Modern equipment and personal trainers'),
	 (127,'Executive Club Lounge – Private check-in and exclusive services'),
	 (128,'Rooftop infinity pool – Stunning city views and poolside service​'),
	 (128,'Winston Grill & Patio – Signature steakhouse with fine wines'),
	 (128,'24-hour fitness center – Fully equipped with the latest machines'),
	 (128,'Executive Lounge – Private space with food, drinks, and business services'),
	 (128,'Personalized concierge service – Curated experiences around the city');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (129,'Private beach – Exclusive white-sand shores for guests only​'),
	 (129,'Six Senses Spa – Award-winning wellness and relaxation treatments'),
	 (129,'La Yola Restaurant – Fresh Mediterranean seafood by the marina'),
	 (129,'Personal villa manager – Personalized services for each guest'),
	 (129,'Complimentary golf cart – Explore the resort with ease'),
	 (130,'Private beach club – Crystal-clear waters and luxury cabanas​'),
	 (130,'Solaya Spa – Tailored treatments inspired by the Caribbean'),
	 (130,'Mediterraneo Restaurant – Fine Mediterranean cuisine'),
	 (130,'Kids` Club – Activities and services for younger guests'),
	 (130,'Fitness center – Fully equipped and offering yoga classes');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (131,'Private pools – Exclusive pools for Reserve guests​'),
	 (131,'YHI Spa – Wide selection of treatments and therapies'),
	 (131,'Multiple gourmet restaurants – International flavors from around the world'),
	 (131,'Family Concierge – Personalized service for families'),
	 (131,'Fitness center – Modern equipment and daily activities'),
	 (132,'Private beach – Powdery white sand and turquoise waters​'),
	 (132,'Secrets Spa by Pevonia – Luxurious body and beauty treatments'),
	 (132,'Eight gourmet restaurants – À la carte dining experiences'),
	 (132,'Infinity pools – Panoramic views of the Caribbean Sea'),
	 (132,'Personalized concierge service – Tailored luxury experiences');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (133,'​Private white-sand beach – Exclusive and pristine shoreline'),
	 (133,'Balinese-inspired spa – Luxury treatments in tranquil settings'),
	 (133,'DUNE Restaurant – Gourmet dining by Michelin-starred chef Jean-Georges'),
	 (133,'Infinity pool – Overlooking the ocean and surrounded by lush gardens'),
	 (133,'18-hole Ocean Club Golf Course – Designed by Tom Weiskopf'),
	 (134,'​Private beach club – Secluded beachfront experience with luxury service'),
	 (134,'Sense Spa – Holistic therapies inspired by Bahamian traditions'),
	 (134,'Café Boulud The Bahamas – French cuisine by renowned chef Daniel Boulud'),
	 (134,'Exclusive pools – Multiple serene and stylish pool settings'),
	 (134,'Butler service – Personalized, attentive care for every guest');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (135,'​Sense Spa – Award-winning treatments and wellness programs'),
	 (135,'Six restaurants – From authentic Chinese to Western fine dining'),
	 (135,'Indoor swimming pool – Heated and surrounded by garden views'),
	 (135,'Manor Club – Exclusive lounge offering personalized services'),
	 (135,'Art collection – Featuring contemporary Chinese artists throughout the hotel'),
	 (136,'The Peninsula Spa – Holistic wellness treatments and therapies​'),
	 (136,'Jing Restaurant – Award-winning modern French dining'),
	 (136,'Fleet of Rolls-Royce limousines – For stylish transportation'),
	 (136,'Art gallery – Showcasing contemporary Chinese works'),
	 (136,'Indoor pool & fitness center – Top-tier wellness facilities');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (137,'The Peninsula Spa – Holistic wellness with exclusive therapies​'),
	 (137,'Sir Elly’s Restaurant – Michelin-starred European fine dining'),
	 (137,'Rolls-Royce fleet – Chauffeur services with signature Peninsula style'),
	 (137,'Indoor heated pool – With panoramic views of the Bund'),
	 (137,'The Peninsula Academy – Curated cultural experiences'),
	 (138,'​Waldorf Astoria Spa – Signature treatments for ultimate relaxation'),
	 (138,'Pelham’s – Fine French dining with a creative flair'),
	 (138,'Long Bar – Historic cocktail lounge with a rich Shanghai legacy'),
	 (138,'Indoor swimming pool – Elegant setting with a skylight roof'),
	 (138,'Personal concierge – Bespoke city experiences and private tours');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (139,'​ESPA Spa – Holistic treatments blending Indian and European techniques'),
	 (139,'Rooftop infinity pool – Overlooking the city’s skyline'),
	 (139,'Jamavar – Celebrated Indian fine dining restaurant'),
	 (139,'Personal butler service – Tailored luxury for every guest'),
	 (139,'Rolls-Royce transfers – Exclusive chauffeur-driven experiences'),
	 (140,'The Imperial Spa – Renowned for bespoke Ayurvedic and international therapies​'),
	 (140,'The Spice Route – Legendary Southeast Asian restaurant'),
	 (140,'Heritage rooms and suites – Decorated with authentic colonial-era art'),
	 (140,'Outdoor swimming pool – Serene, garden-surrounded setting'),
	 (140,'Art and history tours – Explore the hotel`s extensive private collection');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (141,'Jiva Spa – Traditional Indian wellness therapies​'),
	 (141,'Wasabi by Morimoto – Michelin-starred Japanese dining'),
	 (141,'Outdoor pool – Overlooking the Arabian Sea'),
	 (141,'Palace Lounge – Exclusive privileges for Palace Wing guests'),
	 (141,'Heritage walks – Guided tours through the hotel`s historic corridors'),
	 (142,'​Iridium Spa – Bespoke wellness and beauty treatments'),
	 (142,'Seven dining venues – From Asian fusion to fine Indian cuisine'),
	 (142,'Outdoor infinity pool – Skyline views from the 10th floor'),
	 (142,'Signature St. Regis butler service – Personalized attention at any hour'),
	 (142,'Luna – Rooftop bar and restaurant with panoramic cityscapes');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (143,'The Spa at The Ritz-Carlton – Signature treatments for relaxation and rejuvenation​'),
	 (143,'Pearl Chinese Restaurant – Authentic Cantonese and dim sum specialties'),
	 (143,'Outdoor pool – Surrounded by lush gardens and city views'),
	 (143,'Ritz-Carlton Club Lounge – Exclusive access with personalized services'),
	 (143,'Fitness center – State-of-the-art equipment and personal trainers'),
	 (144,'The Spa at Mandarin Oriental – Holistic therapies inspired by local traditions​'),
	 (144,'Li Feng – Authentic Chinese cuisine with a modern twist'),
	 (144,'Outdoor pool – Set amidst tropical gardens for a peaceful retreat'),
	 (144,'Orchid Lounge – Afternoon tea and casual dining with city views'),
	 (144,'Fitness center – Fully equipped and offering yoga classes');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (145,'​Iridium Spa – Tailored wellness experiences inspired by local traditions'),
	 (145,'Kayuputi Restaurant – Fine dining with ocean views and Indonesian-inspired dishes'),
	 (145,'Lagoon and private pools – Crystal-clear waters with private villa access'),
	 (145,'St. Regis Butler Service – Personalized, round-the-clock service'),
	 (145,'Beachfront location – Exclusive access to Bali`s stunning beaches'),
	 (146,'​Sacred River Spa – Holistic treatments with a focus on Balinese healing'),
	 (146,'Riverside dining – Fresh, organic dishes with a view of the Ayung River'),
	 (146,'Infinity pool – Overlooking the tropical jungle and rice fields'),
	 (146,'Yoga and wellness center – Daily classes and personalized programs'),
	 (146,'Cultural experiences – Balinese cooking classes, rice terrace walks, and more');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (147,'​The Oriental Spa – Award-winning therapies and traditional Thai massages'),
	 (147,'Le Normandie – Two Michelin-starred French fine dining'),
	 (147,'Riverside pool – Relaxing with panoramic river views'),
	 (147,'Private butler service – Available in all suites'),
	 (147,'Thai cooking school – Authentic culinary experiences'),
	 (148,'​Opium Spa – Luxurious treatments with organic products'),
	 (148,'Chon Thai Restaurant – Authentic Thai cuisine in a historic setting'),
	 (148,'Private boat service – Shuttle along the Chao Phraya River'),
	 (148,'Private pool villas – Ultimate privacy and luxury'),
	 (148,'Muay Thai gym – Traditional Thai boxing training sessions');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (149,'​Wara Cheewa Spa – Holistic treatments inspired by ancient Thai rituals'),
	 (149,'Rice barn-style villas – Private pavilions overlooking rice paddies'),
	 (149,'Cooking school – Hands-on Thai culinary experiences'),
	 (149,'Two infinity pools – Stunning mountain and field views'),
	 (149,'Yoga and meditation sessions – Daily classes in serene settings'),
	 (150,'Nitra Serenity Centre – Bespoke spa and wellness treatments​'),
	 (150,'Palette Restaurant – Fine dining in an intimate setting'),
	 (150,'Outdoor pool – Surrounded by tropical gardens'),
	 (150,'Private butler service – Personalized attention for all guests'),
	 (150,'Historic architecture tours – Explore the hotel’s storied past');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (151,'Aman Spa – Personalized wellness programs and healing therapies​'),
	 (151,'Private beach – Direct access to a pristine, exclusive shoreline'),
	 (151,'Fine dining – Global and Thai cuisine with panoramic sea views'),
	 (151,'Watersports center – Yachting, diving, and paddleboarding experiences'),
	 (151,'Fitness pavilion – Yoga, Pilates, and Muay Thai classes'),
	 (152,'Asaya Spa – Integrative wellness journeys and personalized therapies​'),
	 (152,'Private pool villas – Spacious indoor-outdoor living'),
	 (152,'Ta Khai Restaurant – Authentic Thai cuisine in a rustic beachfront setting'),
	 (152,'Free-form infinity pool – Overlooking the Andaman Sea'),
	 (152,'Eco-friendly initiatives – Sustainable luxury practices throughout the resort');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (153,'​Aman Spa – Japanese healing rituals and a 30-meter indoor pool'),
	 (153,'Fine dining – Elegant Japanese and Italian cuisine'),
	 (153,'Traditional tea ceremony room – Authentic cultural experiences'),
	 (153,'Library and lounge – Panoramic views across the metropolis'),
	 (153,'Personal wellness programs – Tailored fitness and mindfulness sessions'),
	 (154,'​The Peninsula Spa – Award-winning treatments with Eastern and Western techniques'),
	 (154,'Peter Restaurant – Stylish rooftop dining with cityscape views'),
	 (154,'Indoor pool – Sun-lit and surrounded by greenery'),
	 (154,'Rolls-Royce fleet – Exclusive chauffeur services available'),
	 (154,'Peninsula Academy – Curated Tokyo cultural experiences');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (155,'​Signature St. Regis Butler Service – Personalized attention anytime'),
	 (155,'Rue d’Or Restaurant – Authentic French bistro experience'),
	 (155,'Zen garden terrace – Tranquil outdoor space with city views'),
	 (155,'Iridium Spa – Luxurious treatments inspired by global traditions'),
	 (155,'Fitness center – Modern equipment with personal training available'),
	 (156,'​Conrad Spa – Personalized wellness and beauty treatments'),
	 (156,'Sky Bar & Lounge – Cocktails with dramatic skyline views'),
	 (156,'Indoor pool – Overlooking Osaka`s dazzling cityscape'),
	 (156,'Michelin-starred dining – Innovative Japanese and Western cuisine'),
	 (156,'Art installations – Contemporary artworks throughout the hotel');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (157,'​Private beach access – Exclusive for guests'),
	 (157,'Talise Spa – Sky-high treatments with panoramic views'),
	 (157,'Nine signature restaurants – Including the famous Al Mahara underwater dining'),
	 (157,'Terrace pools – Infinity and freshwater pools over the Arabian Gulf'),
	 (157,'24/7 butler service – Ultimate personalized care'),
	 (158,'​Cloud 22 Sky Pool – Rooftop infinity pool with sweeping views'),
	 (158,'Awaken Spa – Advanced wellness therapies and luxury treatments'),
	 (158,'Private beach club – Elite relaxation and entertainment'),
	 (158,'Celebrity chef restaurants – Dining by the world’s top culinary names'),
	 (158,'Waterpark access – Complimentary entry to Aquaventure Waterpark');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (159,'​Private beach – Over 1.3 km of pristine shoreline'),
	 (159,'Emirates Palace Spa – Arabian-inspired treatments and hammam rituals'),
	 (159,'Fine dining restaurants – Including Michelin-starred venues'),
	 (159,'Outdoor pools – Family-friendly and adults-only options'),
	 (159,'Exclusive chauffeur service – Rolls-Royce and Maybach fleet available'),
	 (160,'St. Regis Butler Service – 24/7 personalized service for every guest​'),
	 (160,'Nation Riviera Beach Club – Private beach and pool access'),
	 (160,'Remède Spa – Signature facials and body therapies'),
	 (160,'Villa Toscana Restaurant – Authentic Italian cuisine'),
	 (160,'Abu Dhabi Suite – The world’s highest suspended suite experience');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (161,'Raffles Spa – Holistic treatments and wellness rituals​'),
	 (161,'Legendary Long Bar – Home of the original Singapore Sling cocktail'),
	 (161,'Courtyard suites – Classic colonial charm with modern comforts'),
	 (161,'Butlers on call – Personalized 24-hour butler service'),
	 (161,'Michelin-starred dining – World-class restaurants led by celebrity chefs'),
	 (162,'Rooftop infinity pool – Overlooking Marina Bay Sands and the skyline​'),
	 (162,'La Brasserie – French bistro-style dining with waterfront views'),
	 (162,'The Landing Point – Afternoon tea and cocktails by the bay'),
	 (162,'Wellness center – Spa treatments and fitness facilities'),
	 (162,'Complimentary heritage tours – Discover Singapore’s rich history');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (163,'​Overwater and beach villas – Private pools and panoramic ocean views'),
	 (163,'Waldorf Astoria Spa – Personalized wellness journeys and treatments'),
	 (163,'Terra Restaurant – Fine dining in private treetop pods'),
	 (163,'Private yacht charters – Explore nearby atolls and islands'),
	 (163,'Butler service – 24/7 personalized attention for all guests'),
	 (164,'​Iridium Spa – Overwater spa with stunning ocean views'),
	 (164,'Whale Bar – Iconic sunset lounge shaped like a whale shark'),
	 (164,'Private villa pools – Secluded relaxation in every accommodation'),
	 (164,'Butler service – Dedicated butler for personalized experiences'),
	 (164,'Diving center – Explore vibrant coral reefs and marine life');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (165,'​Flora Spa by Sisley Paris – Exclusive treatments and wellness programs'),
	 (165,'Outdoor and indoor pools – Surrounded by tropical greenery'),
	 (165,'Tangará Jean-Georges Restaurant – Michelin-starred gastronomy'),
	 (165,'Terrace Lounge – Cocktails and afternoon tea with park views'),
	 (165,'24/7 concierge service – Personalized recommendations and arrangements'),
	 (166,'​Skye Bar & Restaurant – Rooftop dining with spectacular skyline views'),
	 (166,'Rooftop pool – Red-tiled infinity pool with a lively atmosphere'),
	 (166,'Unique Spa by Caudalie – French luxury treatments and rituals'),
	 (166,'Fitness center – Fully equipped with personal training options'),
	 (166,'Art and design tours – Explore the hotel’s unique architecture and interiors');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (167,'Copacabana Beach access – Private area for guests​'),
	 (167,'Pérgula Restaurant – Brazilian and Mediterranean fine dining'),
	 (167,'Exclusive spa – Treatments inspired by Brazilian traditions'),
	 (167,'Semi-Olympic outdoor pool – One of the largest in Rio'),
	 (167,'24/7 concierge service – Personalized city experiences'),
	 (168,'​Rooftop infinity pool – Stunning views over Ipanema and Leblon beaches'),
	 (168,'Fasano Al Mare – Renowned seafood and Italian cuisine'),
	 (168,'Fasano Spa – Holistic treatments and wellness programs'),
	 (168,'Private beach service – Luxury sun loungers and exclusive amenities'),
	 (168,'Personalized concierge – Tailored experiences across Rio');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (169,'​Cielo Spa – Award-winning treatments inspired by Argentine traditions'),
	 (169,'Pony Line Bar – Chic cocktails in a stylish polo-club setting'),
	 (169,'Nuestro Secreto – Open-air Argentine grill restaurant'),
	 (169,'Outdoor heated pool – Set in lush gardens'),
	 (169,'24-hour concierge – Tailored city experiences and excursions'),
	 (170,'Alvear Spa & Fitness Center – Wellness with rooftop views​'),
	 (170,'L`Orangerie – Legendary breakfast and afternoon tea service'),
	 (170,'La Bourgogne – Fine French cuisine by a Michelin-starred chef'),
	 (170,'Indoor heated pool – Overlooking the city skyline'),
	 (170,'Butler service – Personalized attention for every guest');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (171,'Yaku Spa – Signature treatments and relaxing therapies​'),
	 (171,'Perroquet Restaurant – Award-winning Peruvian cuisine'),
	 (171,'English Bar – Home of the original Pisco Sour in Lima'),
	 (171,'Outdoor pool – Elegant courtyard setting'),
	 (171,'24/7 concierge service – Personalized experiences and city tours'),
	 (172,'Full-service spa – Massages, facials, and wellness treatments​'),
	 (172,'La Vista Restaurant – Peruvian and international buffet specialties'),
	 (172,'JW Lounge – Elegant cocktails and fine wines'),
	 (172,'Outdoor pool – Overlooking the Pacific Ocean'),
	 (172,'Executive lounge access – Exclusive services and panoramic views');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (173,'​Rooftop spa and pool – Panoramic views of the Andes'),
	 (173,'Estro Restaurant – Farm-to-table Chilean cuisine'),
	 (173,'Ritz-Carlton Club Lounge – Exclusive experiences and services'),
	 (173,'24-hour fitness center – State-of-the-art equipment'),
	 (173,'Personalized concierge – Curated city tours and excursions'),
	 (174,'Outdoor lagoon-style pool – Lush gardens and cascading waterfalls​'),
	 (174,'Senso Restaurant – Mediterranean and Chilean fusion cuisine'),
	 (174,'Akun Lounge & Bar – Creative cocktails and relaxed ambiance'),
	 (174,'MO Fitness & Wellness – High-end gym and holistic treatments'),
	 (174,'Chauffeur service – Luxury transfers and sightseeing trips');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (175,'​Rooftop heated pool – Overlooking Sydney Harbour'),
	 (175,'The Dining Room – Fine Australian cuisine with harbor views'),
	 (175,'Spa and wellness center – Signature treatments and massages'),
	 (175,'24-hour butler service – Personalized attention for every guest'),
	 (175,'Private balconies – In all rooms and suites'),
	 (176,'Day Spa by Chuan – Award-winning wellness treatments​'),
	 (176,'Indoor heated pool – With a star-dappled ceiling'),
	 (176,'Kitchens on Kent – Interactive dining and gourmet buffets'),
	 (176,'Afternoon tea with Wedgwood – Traditional and elegant experience'),
	 (176,'24/7 concierge service – Curated city tours and exclusive activities');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (177,'​Crown Spa – Award-winning wellness center'),
	 (177,'Crystal Club – Exclusive lounge access and services'),
	 (177,'Indoor heated pool – Elegant surroundings with city views'),
	 (177,'Premium restaurants – Including Nobu and Dinner by Heston Blumenthal'),
	 (177,'24-hour concierge – Personalized experiences across Melbourne'),
	 (178,'​Chuan Spa – Holistic treatments based on Traditional Chinese Medicine'),
	 (178,'Melba Restaurant – International gourmet dining'),
	 (178,'Indoor heated pool – With a rooftop view over the city'),
	 (178,'Afternoon tea with Wedgewood – A signature tradition'),
	 (178,'24/7 concierge service – Bespoke itineraries and private tours');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (179,'Outdoor infinity pool – With sweeping harbor views​'),
	 (179,'Onemata Restaurant – Modern New Zealand cuisine'),
	 (179,'The Spa – Holistic treatments and wellness rituals'),
	 (179,'Fitness center – State-of-the-art equipment'),
	 (179,'24-hour concierge service – Tailored experiences and tours'),
	 (180,'So Spa – French-inspired wellness treatments​'),
	 (180,'Lava Dining – Innovative local and international cuisine'),
	 (180,'Indoor lap pool – Heated for year-round swimming'),
	 (180,'24/7 fitness center – Fully equipped gym facilities'),
	 (180,'Private marina access – For exclusive harbor tours');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (181,'​Outdoor pool – Facing the harbor and gardens'),
	 (181,'Levuka Restaurant – Fine international and Fijian cuisine'),
	 (181,'GPH Spa – Rejuvenating treatments and massages'),
	 (181,'Heritage Lounge – Afternoon tea and classic cocktails'),
	 (181,'24-hour concierge service – Cultural tours and personalized activities'),
	 (182,'​Outdoor pool – With views over the Suva waterfront'),
	 (182,'Bati ni Wai Restaurant – Fresh seafood and local dishes'),
	 (182,'Tapa Lounge Bar – Casual dining and cocktails'),
	 (182,'24/7 fitness center – Modern gym facilities'),
	 (182,'Business center – Fully equipped for meetings and events');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (183,'​Sofitel Spa – Holistic treatments and beachfront massages'),
	 (183,'Waitui Beach Club – Adults-only luxury area with pool and bar'),
	 (183,'Bazaar Kitchen & Bar – International interactive dining'),
	 (183,'Outdoor lagoon pool – Surrounded by tropical gardens'),
	 (183,'24/7 concierge service – Personalized island excursions'),
	 (184,'Blu Spa – Full-service treatments and beauty therapies​'),
	 (184,'Lagoon-style swimming pools – Including adults-only areas'),
	 (184,'Signature Chantara Thai Restaurant – Award-winning cuisine'),
	 (184,'Private beach access – Watersports and activities available'),
	 (184,'Concierge desk – Tailored tours and cultural experiences');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (185,'SpaHalekulani – Award-winning holistic spa treatments​'),
	 (185,'House Without A Key – Legendary oceanfront dining and live music'),
	 (185,'La Mer – Hawaii’s only AAA Five Diamond restaurant'),
	 (185,'Heated freshwater pool – Iconic mosaic orchid design'),
	 (185,'24/7 concierge service – Custom cultural and island experiences'),
	 (186,'​Abhasa Spa – Tropical garden spa treatments'),
	 (186,'Azure Restaurant – Ocean-to-table seafood dining'),
	 (186,'Private beachfront – Reserved areas for guests only'),
	 (186,'Helumoa Playground – Pools and whirlpools overlooking Waikiki Beach'),
	 (186,'24-hour concierge – Exclusive tours and cultural activities');
INSERT INTO travel_db.hotel_services (hotel_id,text) VALUES
	 (187,'​Deep Nature Spa – Traditional Tahitian treatments'),
	 (187,'Lagoonarium – Natural aquarium for snorkeling'),
	 (187,'Le Lotus Restaurant – Gourmet French-Polynesian cuisine'),
	 (187,'Infinity pool – Overlooking the turquoise lagoon'),
	 (187,'24/7 concierge service – Excursions, diving, and cultural tours'),
	 (188,'​Largest outdoor pool in Tahiti – Oceanfront with cabanas'),
	 (188,'Moevai Restaurant – International and Polynesian fusion cuisine'),
	 (188,'Vaipuna Pool Bar – Relaxed cocktails by the pool'),
	 (188,'Spa and wellness center – Massages and holistic therapies'),
	 (188,'24-hour concierge – Customized island excursions');
