INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (1,'Le Cinq','31 Avenue George V, 75008 Paris','https://i.imgur.com/fxqwJRl.png','$$$'),
	 (1,'Arpège','84 Rue de Varenne, 75007 Paris','https://i.imgur.com/94HiFEC.png','$$$'),
	 (1,'Bistrot Paul Bert','18 Rue Paul Bert, 75011 Paris','https://i.imgur.com/6pQnV2E.png','$$'),
	 (1,'Bouillon Pigalle','22 Boulevard de Clichy, 75018 Paris','https://i.imgur.com/E7PiqMd.png','$'),
	 (2,'Le Chantecler','37 Promenade des Anglais, 06000 Nice','https://i.imgur.com/31zMG4g.png','$$$'),
	 (2,'JAN','12 Rue Lascaris, 06300 Nice','https://i.imgur.com/szMwPo4.png','$$$'),
	 (2,'La Voglia','2 Rue Saint-François de Paule, 06300 Nice','https://i.imgur.com/uvRJHDN.png','$$'),
	 (2,'Chez Palmyre','5 Rue Droite, 06300 Nice','https://i.imgur.com/0iG9eNU.png','$'),
	 (3,'DiverXO','Calle Padre Damián, 23, 28036 Madrid','https://i.imgur.com/9Gy6bTa.png','$$$'),
	 (3,'Santceloni','Paseo de la Castellana, 57, 28046 Madrid','https://i.imgur.com/KidOdIW.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (3,'Casa Mono','Calle del Tutor, 37, 28008 Madrid','https://i.imgur.com/OsrR0uQ.jpeg','$$'),
	 (3,'WELKHOMEclub','C. del Monte Esquinza, 15, Chamberí, 28010 Madrid','https://i.imgur.com/57n45c5.png','$$'),
	 (4,'Lasarte','Carrer de Mallorca, 259, 08008 Barcelona','https://i.imgur.com/Hr1hFvG.png','$$$'),
	 (4,'ABaC','Avinguda del Tibidabo, 1, 08022 Barcelona','https://i.imgur.com/lQLUchc.png','$$$'),
	 (4,'Ciudad Condal','Rambla de Catalunya, 18, 08007 Barcelona','https://i.imgur.com/vM8HJZx.png','$$'),
	 (4,'La Paradeta','Carrer Comercial, 7, 08003 Barcelona','https://i.imgur.com/C8hQtyj.png','$'),
	 (5,'La Pergola','Via Alberto Cadlolo, 101, 00136 Rome','https://i.imgur.com/Vr1VrJN.png','$$$'),
	 (5,'Imàgo','Piazza Trinità dei Monti, 6, 00187 Rome','https://i.imgur.com/MCrRNmb.png','$$$'),
	 (5,'Roscioli','Via dei Giubbonari, 21/22, 00186 Rome','https://i.imgur.com/ZotVExE.jpeg','$$'),
	 (5,'Pizzeria Ai Marmi','Viale Trastevere, 53, 00153 Rome','https://i.imgur.com/bhI7t2I.png','$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (6,'Seta','Via Andegari, 9, 20121 Milan','https://i.imgur.com/IfPrgOJ.png','$$$'),
	 (6,'Cracco','Galleria Vittorio Emanuele II, 20121 Milan','https://i.imgur.com/RYtu4ua.png','$$$'),
	 (6,'Trattoria Milanese','Via Santa Marta, 11, 20123 Milan','https://i.imgur.com/rMNE2rZ.png','$$'),
	 (6,'Luini','Via Santa Radegonda, 16, 20121 Milan','https://i.imgur.com/TGFGQ0m.png','$'),
	 (7,'Oro Restaurant','Giudecca, 10, 30133 Venice','https://i.imgur.com/9zw6EIS.jpeg','$$$'),
	 (7,'Quadri','Piazza San Marco, 121, 30124 Venice','https://i.imgur.com/LOjE1QC.jpeg','$$$'),
	 (7,'Antiche Carampane','Rio Terà de le Carampane, 1911, 30125 Venice','https://i.imgur.com/Qy8Jbz1.png','$$'),
	 (7,'Dal Moro''s Fresh Pasta To Go','Calle Casseleria, 5324, 30122 Venice','https://i.imgur.com/WMF125S.png','$'),
	 (8,'Restaurant Gordon Ramsay','68 Royal Hospital Rd, London SW3 4HP','https://i.imgur.com/IUZ5qVg.png','$$$'),
	 (8,'Alain Ducasse at The Dorchester','53 Park Ln, London W1K 1QA','https://i.imgur.com/dArdRea.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (8,'Dishoom Covent Garden','12 Upper St Martin''s Ln, London WC2H 9FB','https://i.imgur.com/xxyl6cR.png','$$'),
	 (8,'Franco Manca','51 Berwick St, London W1F 8SJ','https://i.imgur.com/4jzDjgv.png','$'),
	 (9,'The Kitchin','78 Commercial St, Edinburgh EH6 6LX','https://i.imgur.com/a1V5UBa.png','$$$'),
	 (9,'Number One at The Balmoral','1 Princes St, Edinburgh EH2 2EQ','https://i.imgur.com/mClJHQn.png','$$$'),
	 (9,'The Outsider','15-16 George IV Bridge, Edinburgh EH1 1EE','https://i.imgur.com/hQYhybA.png','$$'),
	 (9,'Oink','34 Victoria St, Edinburgh EH1 2JW','https://i.imgur.com/8Qu1ELW.png','$'),
	 (10,'Steirereck','Am Heumarkt 2A, 1030 Vienna','https://i.imgur.com/eWUHXbj.png','$$$'),
	 (10,'Mraz & Sohn','Wallensteinstraße 59, 1200 Vienna','https://i.imgur.com/RMmpA6g.png','$$$'),
	 (10,'Plachutta Wollzeile','Wollzeile 38, 1010 Vienna','https://i.imgur.com/1KO6ddb.png','$$'),
	 (10,'','Weihburggasse 17, 1010 Vienna','https://i.imgur.com/gX62lKW.png','$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (11,'Ikarus','Wilhelm-Spazier-Straße 7A, 5020 Salzburg, Austria','https://i.imgur.com/WzwgzFO.png','$$$'),
	 (11,'Esszimmer','Müllner Hauptstraße 33, 5020 Salzburg, Austria','https://i.imgur.com/M3p3Ig8.jpeg','$$$'),
	 (11,'St. Peter Stiftskulinarium','St. Peter Bezirk 1/4, 5020 Salzburg, Austria','https://i.imgur.com/wHVGP87.png','$$'),
	 (11,'Bärenwirt','Müllner Hauptstraße 8, 5020 Salzburg, Austria','https://i.imgur.com/uy7GvLU.jpeg','$'),
	 (12,'Sense Hotel Rooftop Bar','16 Tsar Osvoboditel Blvd, 1000 Sofia, Bulgaria','https://i.imgur.com/k3w09FW.png','$$$'),
	 (12,'Sasa Asian Pub','12 Tsar Osvoboditel Blvd, 1000 Sofia, Bulgaria','https://i.imgur.com/G6SG20x.png','$$$'),
	 (12,'Made in Home','30A Angel Kanchev St, 1000 Sofia, Bulgaria','https://i.imgur.com/2Kw88r6.png','$$'),
	 (12,'Hadjidraganov`s Houses','75 Kozloduy St, 1202 Sofia, Bulgaria','https://i.imgur.com/7tZ6WFI.png','$'),
	 (13,'Captain Cook','Varna Port 9000 Varna, Bulgaria','https://i.imgur.com/XLRDEKs.png','$$$'),
	 (13,'The Sea Terrace','Primorski Blvd 3, 9000 Varna, Bulgaria','https://i.imgur.com/0Ap792a.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (13,'Happy Bar & Grill Center','8 Slivnitsa Blvd, 9000 Varna, Bulgaria','https://i.imgur.com/tsvlpOH.png','$$'),
	 (13,'Staria Chinar','26 Otets Paisiy St, 9000 Varna, Bulgaria','https://i.imgur.com/ml9CHsU.png','$$'),
	 (14,'Frantzén','Klara Norra Kyrkogata 26, 111 22 Stockholm, Sweden','https://i.imgur.com/jnP8ZHy.jpeg','$$$'),
	 (14,'Oaxen Krog','Beckholmsbron 26, 115 21 Stockholm, Sweden','https://i.imgur.com/zZYyOCc.png','$$$'),
	 (14,'Pelikan','Blekingegatan 40, 116 62 Stockholm, Sweden','https://i.imgur.com/yX8KptU.png','$$'),
	 (14,'Meatballs for the People','Nytorgsgatan 30, 116 40 Stockholm, Sweden','https://i.imgur.com/s02zrpL.jpeg','$'),
	 (15,'Bhoga','Norra Hamngatan 10, 411 14 Gothenburg, Sweden','https://i.imgur.com/Zl1j5el.png','$$$'),
	 (15,'Koka','Viktoriagatan 12, 411 25 Gothenburg, Sweden','https://i.imgur.com/toz3rYN.png','$$$'),
	 (15,'Smaka','Vasaplatsen 3, 411 26 Gothenburg, Sweden','https://i.imgur.com/OzhvbZv.png','$$'),
	 (15,'Hagabions Café','Linnégatan 21, 413 04 Gothenburg, Sweden','https://i.imgur.com/PVxh56o.png','$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (16,'Zitouni','1113 Corniche El Nil, Cairo, Egypt','https://i.imgur.com/GzQIHNa.png','$$$'),
	 (16,'Sequoia','53 Abou El Feda, Zamalek, Cairo, Egypt','https://i.imgur.com/k0X0nHh.png','$$$'),
	 (16,'Abou El Sid','157 26th of July Corridor, Zamalek, Cairo, Egypt','https://i.imgur.com/jEqR9iS.png','$$'),
	 (16,'Koshary Abou Tarek','16 Champollion St, Downtown, Cairo, Egypt','https://i.imgur.com/IXa5es6.png','$'),
	 (17,'Byblos','399 El Geish Rd, San Stefano, Alexandria, Egypt','https://i.imgur.com/1X1hTUr.png','$$$'),
	 (17,'Fish Market','El Corniche Rd, Alexandria, Egypt','https://i.imgur.com/jtCf82q.png','$$'),
	 (17,'Balbaa Village','El Montaza, Alexandria, Egypt','https://i.imgur.com/wzmNgq0.png','$$'),
	 (18,'Rick`s Café','248 Blvd Sour Jdid, Casablanca 20250, Morocco','https://i.imgur.com/17GYtko.png','$$$'),
	 (18,'La Sqala','Boulevard des Almohades, Casablanca 20250, Morocco','https://i.imgur.com/G4ej9YS.jpeg','$$$'),
	 (18,'Le Cabestan','90, Boulevard de la Corniche, Casablanca 20000, Morocco','https://i.imgur.com/AAJYpzz.png','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (19,'La Grande Table Marocaine','Rue Abou Abbas El Sebti, Marrakesh','https://i.imgur.com/DPgYxtO.png','$$$'),
	 (19,'Dar Yacout','79 Derb Sidi Ahmed Soussi, Marrakesh','https://i.imgur.com/JUBj32W.png','$$$'),
	 (19,'Nomad','1 Derb Aarjane, Marrakesh','https://i.imgur.com/lTgkrw4.png','$$'),
	 (19,'Café Clock','224 Derb Chtouka, Marrakesh','https://i.imgur.com/yArSknW.jpeg','$'),
	 (20,'Marble','Trumpet on Keyes, Rosebank, Johannesburg','https://i.imgur.com/Fx6MJPF.png','$$$'),
	 (20,'DW Eleven-13','Dunkeld West Centre, Johannesburg','https://i.imgur.com/T97y2G7.png','$$$'),
	 (20,'The Local Grill','7th Ave, Parktown North, Johannesburg','https://i.imgur.com/UdfRMnt.png','$$'),
	 (20,'Vuyos','Vilakazi St, Soweto, Johannesburg','https://i.imgur.com/Gw6b6eL.png','$'),
	 (21,'La Colombe','Silvermist Estate, Constantia Nek, Cape Town','https://i.imgur.com/uSOsLjg.png','$$$'),
	 (21,'FYN','37 Parliament St, CBD, Cape Town','https://i.imgur.com/IUWX3pF.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (21,'Chef`s Warehouse at Beau Constantia','Beau Constantia, Cape Town','https://i.imgur.com/4QNy93g.png','$$'),
	 (21,'The Foodbarn','Noordhoek Farm Village, Cape Town','https://i.imgur.com/D1Vqb12.png','$'),
	 (22,'Talisman','320 Ngong Road, Karen, Nairobi','https://i.imgur.com/KGEWOZg.png','$$$'),
	 (22,'Cave à Manger','Dagoretti Rd, Nairobi','https://i.imgur.com/YbOgQQC.png','$$$'),
	 (22,'Canopy Cafe','Wood Avenue, Nairobi','https://i.imgur.com/4nOYjnk.png','$$'),
	 (22,'Mama Oliech Restaurant','Marcus Garvey Rd, Nairobi','https://i.imgur.com/EHBebdi.png','$'),
	 (23,'Leo`s at the Castle','Heinitzburg Castle, Windhoek','https://i.imgur.com/5VIgIT6.jpeg','$$$'),
	 (23,'Stellenbosch Wine Bar & Bistro','Windhoek','https://i.imgur.com/wCxlat1.png','$$$'),
	 (23,'Social','Windhoek','https://i.imgur.com/gxPxjDK.png','$$'),
	 (23,'Joe`s Beerhouse','160 Nelson Mandela Ave, Windhoek','https://i.imgur.com/ZFCHpK4.png','$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (24,'Marie-Antoinette','B. Serret Road, Victoria','https://i.imgur.com/1vrpx25.png','$$$'),
	 (24,'Coco Blu','Francis Rachel Street, Victoria','https://i.imgur.com/f0Pv5Xu.png','$$$'),
	 (24,'Moloko','Pierre Possession Street, Victoria','https://i.imgur.com/DIaipk0.png','$$'),
	 (25,'La Plage Restaurant','Beau Vallon Beach, Seychelles','https://i.imgur.com/OfX8OTT.png','$$$'),
	 (25,'Boat House','Beau Vallon, Seychelles','https://i.imgur.com/vUNF6iG.png','$$$'),
	 (25,'Baobab Pizzeria','Beau Vallon, Seychelles','https://i.imgur.com/QyjoQ7T.png','$$'),
	 (25,'The Copper Pot','Beau Vallon, Seychelles','https://i.imgur.com/glx1Y0s.png','$'),
	 (26,'Providence','5955 Melrose Ave, Los Angeles, CA','https://i.imgur.com/8Rg5wxJ.png','$$$'),
	 (26,'n/naka','3455 S. Overland Ave, Los Angeles, CA','https://i.imgur.com/6r1U6Wb.png','$$$'),
	 (26,'Bestia','2121 E. 7th Pl, Los Angeles, CA','https://i.imgur.com/JKWbMsI.png','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (26,'Mesa Thai','Thai Town, Los Angeles, CA','https://i.imgur.com/WtGUmhg.png','$'),
	 (27,'Eleven Madison Park','11 Madison Ave, New York, NY','https://i.imgur.com/xCS438R.png','$$$'),
	 (27,'Per Se','10 Columbus Circle, New York, NY','https://i.imgur.com/xB7rUKA.png','$$$'),
	 (27,'Jean-Georges','1 Central Park West, New York, NY','https://i.imgur.com/vcAIimU.png','$$'),
	 (27,'Birria-Landia','77-99 Roosevelt Ave, Queens, NY','https://i.imgur.com/7nepXUD.png','$'),
	 (28,'Joël Robuchon','3799 Las Vegas Blvd S, Las Vegas, NV','https://i.imgur.com/AsBsMTr.png','$$$'),
	 (28,'é by José Andrés','3708 Las Vegas Blvd S, Las Vegas, NV','https://i.imgur.com/8zDsWIY.png','$$$'),
	 (28,'The Bedford by Martha Stewart','Paris Las Vegas, Las Vegas, NV','https://i.imgur.com/0E9Majm.png','$$'),
	 (28,'Tacos El Gordo','3049 S Las Vegas Blvd, Las Vegas, NV','https://i.imgur.com/frcu4Sc.png','$'),
	 (29,'Alo Restaurant','163 Spadina Ave, Toronto, ON','https://i.imgur.com/HwWO3Kt.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (29,'Sushi Masaki Saito','88 Avenue Rd, Toronto, ON','https://i.imgur.com/wPpTHPu.png','$$$'),
	 (29,'Richmond Station','1 Richmond St W, Toronto, ON','https://i.imgur.com/Z89mSPH.png','$$'),
	 (29,'Seven Lives Tacos','69 Kensington Ave, Toronto, ON','https://i.imgur.com/EpwISjD.png','$'),
	 (30,'Vij`s','3106 Cambie St, Vancouver, BC','https://i.imgur.com/J6d9uuq.png','$$$'),
	 (30,'Miku','200 Granville St, Vancouver, BC','https://i.imgur.com/bcXtxA9.png','$$$'),
	 (30,'The Fish Counter','3825 Main St, Vancouver, BC','https://i.imgur.com/utCTGcF.png','$$'),
	 (30,'Tacofino','15 W Cordova St, Vancouver, BC','https://i.imgur.com/yFz2QaG.png','$'),
	 (31,'Pujol','Tennyson 133, Polanco, Mexico City','https://i.imgur.com/7GPJr6i.jpeg','$$$'),
	 (31,'Quintonil','Newton 55, Polanco, Mexico City','https://i.imgur.com/BiEY0b1.png','$$$'),
	 (31,'Lardo','Agustín Melgar 6, Condesa, Mexico City','https://i.imgur.com/r5Lg4QH.jpeg','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (31,'El Turix','Emilio Castelar 212, Polanco, Mexico City','https://i.imgur.com/pMfk3Zn.png','$'),
	 (32,'Harry`s Prime Steakhouse & Raw Bar','Blvd. Kukulcan Km. 14.2, Cancun','https://i.imgur.com/ZMv5rpW.png','$$$'),
	 (32,'RosaNegra Cancun','Blvd. Kukulcan Km. 15, Cancun','https://i.imgur.com/RptAemj.png','$$$'),
	 (32,'Mextreme','Blvd. Kukulcan Km. 9.5, Cancun','https://i.imgur.com/zwlffKC.png','$$'),
	 (32,'El Fish Fritanga','Blvd. Kukulcan Km. 12.6, Cancun','https://i.imgur.com/YOL3aQr.png','$'),
	 (33,'Santino Cucina e Vino','Calle Andres Julio Aybar, Santo Domingo','https://i.imgur.com/J2VmPIR.png','$$$'),
	 (33,'La Cassina','Av. Gustavo Mejía Ricart, Santo Domingo','https://i.imgur.com/HfOugcu.png','$$$'),
	 (33,'El Conuco','Calle Casimiro de Moya, Santo Domingo','https://i.imgur.com/AMc7qTL.png','$$'),
	 (33,'Adrian Tropical','Av. George Washington, Santo Domingo','https://i.imgur.com/3kltYr9.png','$'),
	 (34,'La Yola','Punta Cana Resort, Punta Cana','https://i.imgur.com/20gVTNp.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (34,'Jellyfish Restaurant','Bávaro Beach, Punta Cana','https://i.imgur.com/rj4VE1v.png','$$$'),
	 (34,'Wacamole','Av. Alemania, Punta Cana','https://i.imgur.com/FwyDY0r.png','$$'),
	 (34,'Kat`s Corner','Calle Pedro Mir, Punta Cana','https://i.imgur.com/VWn8yrC.png','$'),
	 (35,'Graycliff Restaurant','West Hill Street, Nassau','https://i.imgur.com/MY4KTuR.png','$$$'),
	 (35,'JWB Prime Steak and Seafood','Baha Mar Blvd, Nassau','https://i.imgur.com/MgR4NYn.png','$$$'),
	 (35,'Cleo Mediterráneo','Baha Mar Blvd, Nassau','https://i.imgur.com/DDdX5oA.png','$$'),
	 (35,'Arawak Cay Fish Fry','Arawak Cay, Nassau','https://i.imgur.com/oqS6Ujf.png','$'),
	 (36,'TRB Hutong','23 Shatan N St, Dongcheng, Beijing','https://i.imgur.com/UpueGYb.png','$$$'),
	 (36,'Da Dong Roast Duck','Dongsi 10th Alley, Beijing','https://i.imgur.com/YgP2c0A.png','$$$'),
	 (36,'Jingzun Peking Duck Restaurant','Bldg 6, Sanlitun, Beijing','https://i.imgur.com/CWbVQeX.png','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (36,'Siji Minfu','11 Nanchizi St, Dongcheng, Beijing','https://i.imgur.com/f4Yqv94.png','$'),
	 (37,'Ultraviolet by Paul Pairet','Waitan, Shanghai','https://i.imgur.com/bUDYryv.png','$$$'),
	 (37,'M on the Bund','5 Zhongshan East 1st Rd, Shanghai','https://i.imgur.com/LmG8dEN.png','$$$'),
	 (37,'Lost Heaven','17 Yan''an East Rd, Shanghai','https://i.imgur.com/V4lwtQo.png','$$'),
	 (37,'Din Tai Fung','Xintiandi, Shanghai','https://i.imgur.com/3nPtDYM.png','$'),
	 (38,'Indian Accent','77 Friends Colony West, New Delhi','https://i.imgur.com/738rRyL.png','$$$'),
	 (38,'Bukhara','ITC Maurya, New Delhi','https://i.imgur.com/ci1legN.png','$$$'),
	 (38,'Gulati Restaurant','Pandara Road Market, New Delhi','https://i.imgur.com/JD4DKGa.png','$$'),
	 (38,'Rajinder Da Dhaba','Safdarjung Enclave, New Delhi','https://i.imgur.com/gZj9nhj.png','$'),
	 (39,'The Table','Colaba, Mumbai','https://i.imgur.com/xdnE1f7.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (39,'Wasabi by Morimoto','Taj Mahal Palace, Mumbai','https://i.imgur.com/KRkLxep.png','$$$'),
	 (39,'Britannia & Co.','Ballard Estate, Mumbai','https://i.imgur.com/53Fd9Pk.png','$$'),
	 (39,'Bademiya','Colaba, Mumbai','https://i.imgur.com/0MH4Sgg.png','$'),
	 (40,'Amuz Gourmet','SCBD, Jakarta','https://i.imgur.com/AtLpR1L.jpeg','$$$'),
	 (40,'Bistecca','SCBD, Jakarta','https://i.imgur.com/k5npa3x.png','$$$'),
	 (40,'Remboelan','Plaza Senayan, Jakarta','https://i.imgur.com/fFX8pJK.png','$$'),
	 (40,'Sate Khas Senayan','Various Locations, Jakarta','https://i.imgur.com/Z9IDEEG.png','$'),
	 (41,'Mozaic Restaurant Gastronomique','Ubud, Bali','https://i.imgur.com/ediB28u.png','$$$'),
	 (41,'Locavore','Ubud, Bali','https://i.imgur.com/Dq2b7Va.png','$$$'),
	 (41,'Watercress Café','Kerobokan, Bali','https://i.imgur.com/vrSvzzq.png','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (41,'Warung Babi Guling Pak Malen','Seminyak, Bali','https://i.imgur.com/AWL8ThG.png','$'),
	 (42,'Sorn','56 Soi Sukhumvit 26, Khlong Tan, Khlong Toei, Bangkok','https://i.imgur.com/4zQ3Ebi.png','$$$'),
	 (42,'Le Du','399/3 Silom Soi 7, Silom, Bang Rak, Bangkok','https://i.imgur.com/M2yTCGw.png','$$$'),
	 (42,'Nahm','27 South Sathorn Road, Sathorn, Bangkok','https://i.imgur.com/8auLuW3.png','$$'),
	 (42,'Jay Fai','327 Maha Chai Rd, Samran Rat, Phra Nakhon, Bangkok','https://i.imgur.com/TU12Noq.png','$'),
	 (43,'David`s Kitchen','113 Bumrungrad Rd, Wat Ket, Chiang Mai','https://i.imgur.com/Y5xpMY2.jpeg','$$$'),
	 (43,'Ginger & Kafe','199 Mun Mueang Rd, Si Phum, Chiang Mai','https://i.imgur.com/2SehHbA.png','$$$'),
	 (43,'Dash! Restaurant and Bar','38/2 Moon Muang Rd Lane 1, Chiang Mai','https://i.imgur.com/VXDpeKn.png','$$'),
	 (43,'Khao Soi Khun Yai','Sri Poom 8 Alley, Chiang Mai','https://i.imgur.com/LBMcVH0.png','$'),
	 (44,'Acqua Restaurant','324/15 Prabaramee Road, Patong, Kalim, Phuket','https://i.imgur.com/uWnSX5B.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (44,'Blue Elephant Phuket','96 Krabi Road, Talad Nuea, Phuket Town','https://i.imgur.com/Fduxoz8.png','$$$'),
	 (44,'Suay Restaurant','50/2 Takuapa Road, Talad Yai, Phuket Town','https://i.imgur.com/LMAyWfh.jpeg','$$'),
	 (44,'No.6 Restaurant','Thanon Ratuthit Songroipi Rd, Patong, Phuket','https://i.imgur.com/c6AKrIb.png','$'),
	 (45,'Sushi Saito','1-4-5 Roppongi, Minato-ku, Tokyo','https://i.imgur.com/POVyadw.png','$$$'),
	 (45,'Sazenka','4-7-5 Minami-Azabu, Minato, Tokyo','https://i.imgur.com/6Dsx3N8.png','$$$'),
	 (45,'Den','2-4-5 Jingumae, Shibuya, Tokyo','https://i.imgur.com/oA7Ijxs.jpeg','$$'),
	 (45,'Ichiran Shibuya','1-22-7 Jinnan, Shibuya, Tokyo','https://i.imgur.com/AeTiLW8.jpeg','$'),
	 (46,'La Cime','3-2-15 Kawaramachi, Chuo-ku, Osaka','https://i.imgur.com/OEHSjXo.png','$$$'),
	 (46,'Hajime','1-9-11 Edobori, Nishi-ku, Osaka','https://i.imgur.com/WgHP9Hi.png','$$$'),
	 (46,'Mizuno','1-4-15 Dotonbori, Chuo-ku, Osaka','https://i.imgur.com/0InoVwr.png','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (46,'Ichiran Dotonbori','7-18 Souemoncho, Chuo-ku, Osaka','https://i.imgur.com/twQeZDX.png','$'),
	 (47,'Torno Subito','W Dubai - The Palm, Palm Jumeirah, Dubai','https://i.imgur.com/v47FQVo.png','$$$'),
	 (47,'Rhain Dubai','Sheikh Zayed Rd, Trade Centre 1, Dubai','https://i.imgur.com/vQidZSf.png','$$$'),
	 (47,'Jun`s','Downtown Dubai, Dubai','https://i.imgur.com/jyV4RqM.png','$$'),
	 (47,'Al Ustad Special Kabab','Al Mankhool Rd, Dubai','https://i.imgur.com/O0Ul07m.png','$'),
	 (48,'Li Beirut','Corniche Rd W, Al Ras Al Akhdar, Abu Dhabi','https://i.imgur.com/ahhRH16.png','$$$'),
	 (48,'Hakkasan Abu Dhabi','Emirates Palace, West Corniche Rd, Abu Dhabi','https://i.imgur.com/z8fyFyD.png','$$$'),
	 (48,'Al Fanar Restaurant & Cafe','Yas Mall, Yas Island, Abu Dhabi','https://i.imgur.com/tbPbhVw.png','$$'),
	 (48,'Automatic Restaurant & Grill','Hamdan St, Abu Dhabi','https://i.imgur.com/3iihM6F.png','$'),
	 (49,'Odette','1 St Andrew''s Rd, #01-04, National Gallery, Singapore','https://i.imgur.com/sQK8P1D.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (49,'Iggy`s','581 Orchard Rd, Hilton Hotel, Singapore','https://i.imgur.com/pmH9ylb.jpeg','$$$'),
	 (49,'Labyrinth','8 Raffles Ave, #02-23, Esplanade Mall, Singapore','https://i.imgur.com/6zKspj0.png','$$'),
	 (49,'Hawker Chan','78 Smith St, Chinatown, Singapore','https://i.imgur.com/M7bZcxT.png','$'),
	 (50,'Ithaa Undersea Restaurant','Conrad Maldives Rangali Island, Maldives','https://i.imgur.com/fqmiqKi.png','$$$'),
	 (50,'Sea.Fire.Salt.','Anantara Dhigu Maldives Resort, Maldives','https://i.imgur.com/KOC04UW.png','$$$'),
	 (50,'Sala Thai Restaurant','Buruneege Hithaffinivaa Magu, Male','https://i.imgur.com/lpLAfus.png','$$'),
	 (50,'Symphony Restaurant','Fareedhee Magu, Male','https://i.imgur.com/jQx5NDQ.png','$'),
	 (51,'D.O.M.','Rua Barão de Capanema, 549, Jardins, São Paulo','https://i.imgur.com/AYgVKA3.png','$$$'),
	 (51,'Maní','Rua Joaquim Antunes, 210, Jardim Paulistano, São Paulo','https://i.imgur.com/TV9GRYX.png','$$$'),
	 (51,'Tordesilhas','Alameda Tietê, 489, Jardins, São Paulo','https://i.imgur.com/sKCpMSw.png','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (51,'Bar do Mané','Rua 25 de Março, 1081, Centro, São Paulo','https://i.imgur.com/cSAwydF.png','$'),
	 (52,'Oro','Rua General San Martin, 889, Leblon, Rio de Janeiro','https://i.imgur.com/qTezqud.png','$$$'),
	 (52,'Lasai','Rua Conde de Irajá, 191, Botafogo, Rio de Janeiro','https://i.imgur.com/mJSlDVx.png','$$$'),
	 (52,'Aprazível','Rua Aprazível, 62, Santa Teresa, Rio de Janeiro','https://i.imgur.com/yWOHOul.png','$$$'),
	 (52,'Confeitaria Colombo','Rua Gonçalves Dias, 32, Centro, Rio de Janeiro','https://i.imgur.com/WryxZYx.jpeg','$$$'),
	 (53,'Don Julio','Guatemala 4699, Palermo, Buenos Aires','https://i.imgur.com/8xeuWBF.png','$$$'),
	 (53,'Tegui','Costa Rica 5852, Palermo, Buenos Aires','https://i.imgur.com/B7cufwp.png','$$$'),
	 (53,'El Preferido de Palermo','Jorge Luis Borges 2108, Palermo, Buenos Aires','https://i.imgur.com/2ddAQaL.png','$$'),
	 (53,'La Brigada','Estados Unidos 465, San Telmo, Buenos Aires','https://i.imgur.com/IQ3FQ8H.jpeg','$'),
	 (54,'Maido','399 San Martin St, Miraflores, Lima','https://i.imgur.com/ggQpQBp.jpeg','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (54,'Central','Santa Isabel 376, Miraflores, Lima','https://i.imgur.com/Wvney1H.png','$$$'),
	 (54,'Isolina','Av. San Martin 101, Barranco, Lima','https://i.imgur.com/eZGvkvH.png','$$'),
	 (54,'La Lucha Sanguchería','Av. Diagonal 308, Miraflores, Lima','https://i.imgur.com/DblGjBI.png','$'),
	 (55,'Boragó','Av. San Josemaría Escrivá de Balaguer 5970, Vitacura, Santiago','https://i.imgur.com/K34Ds9j.png','$$$'),
	 (55,'99 Restaurante','Av. Andrés Bello 2211, Providencia, Santiago','https://i.imgur.com/zHGOQoS.png','$$$'),
	 (55,'Liguria','Av. Providencia 1373, Providencia, Santiago','https://i.imgur.com/Uip6qWa.png','$$'),
	 (55,'Fuente Alemana','Av. Libertador Bernardo O''Higgins 58, Santiago','https://i.imgur.com/75QqmWj.png','$'),
	 (56,'Quay','Overseas Passenger Terminal, The Rocks, Sydney','https://i.imgur.com/wltty8K.png','$$$'),
	 (56,'Bennelong','Bennelong Point, Sydney Opera House, Sydney','https://i.imgur.com/9wMrMjK.png','$$$'),
	 (56,'Chin Chin','69 Commonwealth St, Surry Hills, Sydney','https://i.imgur.com/OggZpqN.png','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (56,'The Grounds of Alexandria','7a/2 Huntley St, Alexandria, Sydney','https://i.imgur.com/UKRZdIa.png','$$'),
	 (57,'Attica','74 Glen Eira Rd, Ripponlea, Melbourne','https://i.imgur.com/fXe6IGI.png','$$$'),
	 (57,'Vue de Monde','Level 55, 525 Collins St, Melbourne','https://i.imgur.com/OuS6hfm.png','$$$'),
	 (57,'Chin Chin','125 Flinders Ln, Melbourne','https://i.imgur.com/5JOcsK7.png','$$'),
	 (57,'Hardware Société','10 Katherine Pl, Melbourne','https://i.imgur.com/Qorge8q.jpeg','$'),
	 (58,'Sidart','283 Ponsonby Rd, Ponsonby, Auckland','https://i.imgur.com/PBm362i.png','$$$'),
	 (58,'Clooney','33 Sale St, Freemans Bay, Auckland','https://i.imgur.com/dYJOW3o.png','$$$'),
	 (58,'Depot Eatery','86 Federal St, Auckland CBD, Auckland','https://i.imgur.com/Qxn2qzt.png','$$'),
	 (58,'The White Lady','18 Commerce St, Auckland CBD, Auckland','https://i.imgur.com/XYkvXw2.png','$'),
	 (59,'Governors Museum Themed Restaurant','46 Knollys St, Suva','https://i.imgur.com/bk7h0b3.png','$$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (59,'Tiko`s Floating Restaurant','Stinson Parade, Suva','https://i.imgur.com/evmiNHT.png','$$$'),
	 (59,'Eden Bistro & Bar','1 Kalokalo Cres, Suva','https://i.imgur.com/6tXqv8y.png','$$'),
	 (59,'Bulaccino Café','Victoria Parade, Suva','https://i.imgur.com/dJjx0yz.png','$'),
	 (60,'Ports O` Call','Denarau Island, Nadi','https://i.imgur.com/2jHapcx.png','$$$'),
	 (60,'Nadina Authentic Fijian Restaurant','Port Denarau, Nadi','https://i.imgur.com/gvWUxej.png','$$$'),
	 (60,'Tu`s Place','Queens Rd, Martintar, Nadi','https://i.imgur.com/uR74d0N.png','$$'),
	 (60,'Bulaccino Café','Namaka, Nadi','https://i.imgur.com/yvyaGmu.png','$'),
	 (61,'Chef Mavro','1969 S King St, Honolulu','https://i.imgur.com/ftNZsN2.png','$$$'),
	 (61,'Alan Wong`s Honolulu','1857 S King St, Honolulu','https://i.imgur.com/oDs2Sqd.png','$$$'),
	 (61,'The Pig and the Lady','83 N King St, Honolulu','https://i.imgur.com/AotEO1n.jpeg','$$');
INSERT INTO travel_db.restaurants (city_id,name,location,image_url,price_symbols) VALUES
	 (61,'Rainbow Drive-In','3308 Kanaina Ave, Honolulu','https://i.imgur.com/1ZD3Xh8.png','$'),
	 (62,'Le Coco`s','PK 14,5, Punaauia, Tahiti','https://i.imgur.com/xB4kp3C.png','$$$'),
	 (62,'Le Lotus','InterContinental Resort, Faa''a, Tahiti','https://i.imgur.com/HgMDKFv.png','$$$'),
	 (62,'Les Roulottes','Place Vaiete, Papeete','https://i.imgur.com/isWDPUv.png','$$'),
	 (62,'Snack Mahana','PK 17,2, Haapiti, Moorea','https://i.imgur.com/jECGtyL.png','$');
